In [60]:
#class work 8-07-2026
name1=["sameer","virat","yuraj"]
name1.append("yash")
name1

['sameer', 'virat', 'yuraj', 'yash']

In [61]:
name1.append(["virat","yuraj"])
name1

['sameer', 'virat', 'yuraj', 'yash', ['virat', 'yuraj']]

In [62]:

name1.extend(["sanket"])
name1

['sameer', 'virat', 'yuraj', 'yash', ['virat', 'yuraj'], 'sanket']

In [63]:

name1.extend(["sumit","piyush"])
name1

['sameer',
 'virat',
 'yuraj',
 'yash',
 ['virat', 'yuraj'],
 'sanket',
 'sumit',
 'piyush']

In [64]:
# remove = when we want to remove specific value then we use remove...
fruits=["Apple","Mango","Apple","Graps","Banana"]
fruits.remove("Apple") ## 1st apple is remove...
fruits
# can we remove 2 item and and list also not remove... because it search one by and it do not search multiple item at a time...

['Mango', 'Apple', 'Graps', 'Banana']

In [65]:
## pop = it removes the elment from spcific position.. if we not mention the index no it revome last item by default..
## if we ge index no that are not present in list then it gives error
fruits=["Apple","Mango","Apple","Graps","Banana"]
fruits.pop(3)
fruits

['Apple', 'Mango', 'Apple', 'Banana']

In [66]:
# clear = It removes all items from list and make list empty.. 
fruits=["Apple","Mango","Apple","Graps","Banana"]
fruits.clear()
fruits

[]

In [67]:
# index = It is used to find the item index no.. we give any list item in paranthesis
# if value is not present it gives error..
fruits=["Apple","Mango","Apple","Graps","Banana"]
fruits.index("Banana")

4

In [68]:
name=["sumit","neha","swati","rahul","pratik"]
name[

_IncompleteInputError: incomplete input (1582189857.py, line 2)

In [ ]:
# count = it is used to count occurence of any item or value we give value in paranthesis if that item is not present it gives output 0
# if we give multiple value at a time to count it given error if we give list then it give output 0..
fruits=["Apple","Mango","Apple","Graps","Banana"]
fruits.count("Apple")

In [ ]:
# sort = it is used to arrange in assending order or desencending ordeer.. by default is asending it is used only when all item are same type
# syntax : list.sort(reverse=false) it gives desending
age=[20,34,54,12,54,34,67]
age.sort()
age

In [ ]:
fruits=["Apple","Mango","Apple","Graps","Banana","#$"]
fruits.sort()
fruits

In [ ]:
# copy =it copy list in another in list..
fruits=["Apple","Mango","Apple","Graps","Banana","#$"]
list2=fruits.copy()
list2

In [ ]:
list3=fruits
list3

In [ ]:
num=int(input("Enter a no: "))
check="Yes" * (num%2==0) or "No"
print(f"A Number is a Even:{check} and A is not odd {check}")

##### Date 09-07-2026

In [ ]:
# Nested List  = list inside list
list1=[1,2,3,4,5,6]
# nested list
List2=[[1,2,3],[4,5,6],[7,8,9]]
List2[2][0]
List2[2][0]=10
List2

In [ ]:
# Tuple : Tuple is Immutable Data type. tuple are closed in the paranthesis. convert tuple to list yes
tup1=("parul",22,"Bharat",45.5,99)
# methods in tuple are index,count,len,min,max,sum

#### Dictionary Data Type

In [ ]:
# Dictionary collection of data and stored in key-value pairs.  It is written in curly Brackets.
# each key Must be Unique,but values can be duplicates. It is mutable . value can be acessed like d[key]
# Methods in dictionary fromkey,keys(),values(),len,get(),items(),pop(),popitem(),update,clear(),copy(),setdefault
dict1={"Name":"Sumit","Age":10,"Mob-N0":123}
print(type(dict1))
dict1

In [ ]:
key=["Name","Age","Mob-no"]
dict2=dict.fromkeys(key,10)
dict2

In [ ]:
key=["A","B","C"]
dict2=dict.fromkeys(key,20)
dict2

In [ ]:
# key
dict1={"Name":"Sumit","Age":10,"Mob-N0":123}
print("Keys=",dict1.keys())
# values
print("Values=",dict1.values())

In [ ]:
# get
dict1.get("Mob-N0")

In [ ]:
# items
dict1.items()

In [ ]:
# pop It require at least one valid argument 
dict1.pop("Mob-N0")

In [ ]:
dict1

In [ ]:
dict4={"Car":"Thar","Model":2026,"Color":"Black"}
dict4.pop("Model")
dict4

In [ ]:
# popitem It only remove last item
dict4={"Car":"Thar","Model":2026,"Color":"Black"}
dict4.popitem()
dict4

In [ ]:
# update only add  and update items in dictionary.
dict4.update({"Engine Type":"20lit"})
print(dict4)

In [ ]:
dict4["Engin_size"]="20lit" # It update existing key value.
print(dict4)

In [ ]:
dict4.update({"Car":"kia"}) 
print(dict4)

##### 10-07-2026

In [ ]:
# set is write inside the curly bracket and collects only unique element in memory. when set run it output pattern is always changes. set is mutable.
# set does not use indexing it uses hash table to store the data in memory.set does not support slicing and indexing part.set only store imutable type 
# of value.
# methods : add,update,pop,remove,clear,copy,discard,union,Intersection,diference,symmetric deference

In [ ]:
# number set
set1={3,5,7,8,5,3,5.7,74}
set1

In [ ]:
# string set
Name={"Sumit","Prabhas","Allu Arjun","Sumit"}
Name

In [ ]:
# Mix type Value
Mix_type={"Sumit",12,"Apple",34.5,"Alia","Apple",34.5}
Mix_type

In [ ]:
Set1={2,3,5,[3,4,6]}

In [ ]:
# add(): Add the elements in set only one argument is allow
srt={1,2,3,4,5,6}
#syntax: set_name.add(elements) 
srt.add(1)
srt

In [ ]:
# update 
sets={3,3,5,2,5,7,87}
sets.update([3,5.8,9,1])
sets

In [ ]:
# empty set
a=set()
a

In [ ]:
# fast memberhip
sets={3,4,6,3,2,67,1}
print(2 in sets)

In [ ]:
# pop It removes only 1st element , 1st it removes the positive integer values 0 closer first priority is positive number
sets={3,4,6,3,2,67,-11}
sets.pop()
sets

In [ ]:
# remove : If we want to remove specific element then remove is use if value is not peresent error is not come..
sets={3,56,3,3,5,9,0,4}
sets.remove(3)
sets

In [ ]:
# discard if value is not prensent error is not come.
sets={4,6,7,3,6,1}
sets.discard(40)
sets

In [ ]:
# clear
sets={4,6,7,3,6,1}
sets.clear()
sets

In [ ]:
# copy
sets={4,6,7,3,6,1}
setscopy=sets.copy()
setscopy

In [ ]:
# Union (|)
sets={4,6,7,3,6,1}
set1={3,3,5,2,5,7,87}

# a=sets | set1
a=sets.union( set1)
a

In [ ]:
# INTERSECTION (&)
sets={4,6,7,3,6,1}
set1={3,3,5,2,5,7,87}
# a=sets & set1
a=sets.intersection(set1)
a

In [ ]:
# Difference (-)
sets={4,6,7,3,6,1}
set1={3,3,5,2,5,7,87}
# a=sets - set1
a=sets.difference(set1)
a

In [ ]:
# Symetric Difference (^)
sets={4,6,7,3,6,1}
set1={3,3,5,2,5,7,87}
a=sets ^ set1
a

In [ ]:
# conditional statement
# If Statement
num=int(input("Enter a number:"))
if num>=0:
    print("Positive no")

In [ ]:
A=True
if A==True:
    print("Yes")

##### 11-07-2026

In [ ]:
# If else
# voter age >=18 and he have a voter ID
age=int(input("Enter a age: "))
Id=input("enter a input in True or False: ")
if age>=18 and Id.lower()=="True".lower():
    print("You are allow to vote")
else:
        print("You are not allow to vote")

In [ ]:
A=20
B=30
print(f"Addition of two number : {A+B}")

In [ ]:
#find even or odd
a=int(input("Enter a number: "))
if a%2==0:
    print(f"Even no is {a}")
else:
    print(f"Odd no is {a}")

In [ ]:
# check Palindrome or not...
a=input("Enter a number: ")
if a.lower()==a[::-1] :
    print("Palindrome number...")
else:
    print("Not Palindrome number...")

In [ ]:
a=input("Enter a number: ")

b="".join(reversed(a))
if a==b:
    print("palindrome")
else:
    print("Not palindrome")

In [ ]:
# if elif else:

# take the user side result percentage check <90 and less than 

per=float(input("Enter a percentage: "))
if per<=90 and per>80:
    print("Excellent result..")
elif per<=80 and per>70:
    print("Average result..")
elif per<=70 and per>45:
    print("Pass result..")
else:
        print("Fail result..")

In [ ]:
# while loop
# positive and negative
num=0
empty_dictionary={}
while num<=10:
    if num>=0:
        empty_dictionary[num]="Positive"
    else:
        empty_dictionary[num]="Negative"
    num+=1
print(empty_dictionary)

In [ ]:
#palindrome the numbers
num=int(input("Enter a number:"))
original=num
reverse=0
while num>0:
        digit=num%10
        reverse=reverse*10+digit
        num=num//10
if reverse==original:
    print("palindrome")
else:
    print("not palindrome")

In [ ]:
# Start number from 1 end the number less than =10 if number is even print square of number 
num=1
empty_list=[]
while num<=10:
    if num%2==0:
        empty_list.append(f"even {num}:{num**2}")
    else:
        empty_list.append(f"odd {num}:{num**3}")
    num+=1
print(empty_list)

In [ ]:
# for loop
lists=["sumit","Sumit","Sumit123","SuMiT","Sumit@123","1234"]
for i in lists:
    if i.isalpha():
        print("Alpha",i)
    elif i.isdigit():
        print("Digit",i)
    elif i.isalnum():
        print("alnum",i)
    elif i.islower():
        print("Lower",i)
    else:
        print("Special character",i)

In [ ]:
for i in range (1,11):
    if i==5:
        break
    elif i%2==0:
        print("even",i)
    else:
        print("Odd",i)

In [ ]:
name=["1234","1324","3424"]
for i in name:
    print(i)
    for j in i:
       print(j)
       if j=="3":
          break

In [ ]:
name=["1234","1324","3424"]
for i in name:
    print(i)
    for j in i:
       if j=="3":
          continue
       print(j)

In [ ]:
list1=["a","b","c","d","e"]
list2=[1,2,3,4,5]
print(dict(zip(list1,list2)))

In [ ]:
list1=["a","b","c","d","e"]
list2=[1,2,3,4,5]
dict1={}
for i in range(len(list1)):
    dict1[list1[i]]=list2[i]
print(dict1)

In [ ]:
# function
# type() = It is use to check the data type of vairiable
# len()=It is use to check the length of vairiable
# id()=It is use to  check the address of vairiable
# abs()=It is use to convert vairiable value into positive
# round()=It is use to take how much values come in vairiable
# pow()=It take 2 input 1 is num and 2nd is power of num calculate power
# min()=It is use to find min value of mutable data types
# max()=It is use to find max value of mutable data types
# sum()=It calculate the summation of  all value  oaf mutable data types
# input()=It is used to  take a input from user
# zip()=It is used to join multiple list to make dictionary used with mutable,tuple
# Type conversion 
# int,float,list,tuple,set
# sequence of function
# range(start,end,range)
# list(range(start,end))
# sorted()= It is  use to sort vairiable in ascending order 
# reversed()=It is use to reverse the vairiable
# enumerate()=It provides the index no  with value 
# Logical Functions
# all([True,True]) op true
# any([False,True]) op false
# List Comprehension= combinde[loop+condition+expression]
# syntax:[expression for item in place condition]
list1=[1,2,3,4,5]
result=["even"  for num in list1 if num%2==0]
result=["even"  if num%2==0 else "odd" for num in list1]
print(result)

In [ ]:
even=[]
odd=[]
result=[even.append(i) if i%2==0 else odd.append(i) for i in range (1,21)]
print("Even number=",even)
print("Odd number=",odd)

In [ ]:
def check(a):
    if a>0:
        print("positive no")
    else:
        print("Negative no")
check(2)

In [ ]:
def info(name,address,city,course,mentor_name):
    return f"My name is {name} \n Address is {address} \n City is {city} \n Course is {course} \n Mentor Name is {mentor_name}"
print(info("sameer","sharda chowk","mouda","data science with ai","sumit"))

In [ ]:
def info(**details):
    for i,j in details.items():
        print(i,j) 

info(name="sameer",address="sharda chowk",city="Mouda",course="Data science with ai",mentor_name="Sumit")

In [ ]:
# lambda function : It is nameless function it is used when we have single statements 
# Syntax Lambda argument:expression
add=lambda x,y:x+y
add(2,5)
# default args:
add=lambda x=45,y=8:x+y
add(y=34)
# Multi args:
add=lambda *args:sum(args)
add(4,5,3,9)
# Multi args and keyword:
f=lambda *args,**kwargs:(args,kwargs)
f(3,4,5,a=3,b=4)

In [ ]:
## If else is used lambda function only if esle is used in lambda funtion
voting=lambda x:"Eligible" if x>18 else "not eligible"
voting(67)

In [ ]:
# nested condition
n=lambda x:("A" if x>=90 else "B" if x>=75 else "C" if x>=60 else "fails")
n(78)
# when yuou want answer in list 
a=lambda x:[x+x]
a(3)

In [ ]:
a=lambda x,a=18:{"Name":x,"age":a}
print(a("sameer",18))

In [ ]:
### map It is used to change every number 
number=[3,4,56,6,6,9]
result=list(map(lambda x:"Even" if x%2==0 else "Odd" ,number))
result

In [ ]:
# filter : it is used to  find out the satisfy condition value
number=[3,4,56,6,6,9]
result=list(filter(lambda x:x%2==0  ,number))
result

In [ ]:
# shallow copy
# It creates a new outer object but share inner object
import copy

list1 = [10, 20, 30]

list2 = copy.copy(list1)

print("Original:", list1)
print("Copy:", list2)
list1[0]=100

print("Original:", list1)
print("Copy:", list2)

In [ ]:
a=[1,[2,3]]

b=copy.copy(a)
print(a)
print(b)
b[1][0]=22
print(a)
print(b)

In [ ]:
# deep copy it create a new object and new copy and copy the value if any copy changes they does not affect the another range
# In deep copy all values are copied not copy addrres 
import copy

list1 = [10, 20, 30]

list2 = copy.deepcopy(list1)

list2[0] = 100

print(list1)
print(list2)

In [ ]:
import copy

list1 = [1, 2, [3, 4]]

list2 = copy.deepcopy(list1)

list2[2][0] = 100

print(list1)
print(list2)
print(list

In [ ]:
# oops concept
 class Class_name:
     #constructor # It works automatically when we create a  class object
     def __init__(self,args,args):
         self.variable_name=args
         self.variable_name=args
     def method_name(self):
         #behaviour

In [ ]:
class Students:
    def class_name(self,name):
        print("Student class_name=",name)
s1=Students()
s1.class_name("sameer")

In [ ]:
class Student:
    # instance method
    def student_info(self,name,roll_no,class_n):
        self.Name=name
        self.Roll_number=roll_no
        self.Class_name=class_n
    def display(self):
        print("name=",self.Name)
        print("Roll_no=",self.Roll_number)
        print("Class_name=",self.Class_name)
s1=Student()
s1.student_info("Sameer",18,"Data Science")
s1.display()

In [ ]:
# Bank Management system
class Bank_Management:
    #class attribute
    bank_name="State Bank of India"
    # create constructor
    def __init__(self,ac_no,bla,branch):
        self.Account_number=ac_no
        self.Balance=bla
        self.Branch=branch
    # display  the all attribute
    # method 1
    def display_bank_details(self):
        print("Account Number =",self.Account_number)
        print("Balance=",self.Balance)
        print("Branch=",self.Branch)
        print("Bank_name=",Bank_Management.bank_name)
    # method 2 deposit money
    def deposit(self,amount):
        if amount>0:
            self.Balance+=amount
            print(f"Deposit {self.Balance} money successfully Done")
    # method 3 withdraw money
    def withdraw(self,amount):
        if amount<=0:
            print("Invalid amount")
        elif amount>self.Balance:
            print("Insufficient balance")
        else:
            self.Balance-=amount
            print(f"Withraw amount is {amount}")
            print(f"Balance is {self.Balance}")
cst1=Bank_Management(32432418,8000,"Ameerpet")
cst1.display_bank_details()
cst1.deposit(6000)
cst1.withdraw(9000)
print("#"*40)
cst1=Bank_Management(32489410,8000,"Charminar")
cst1.display_bank_details()
cst1.deposit(8000)
cst1.withdraw(5000)

In [ ]:
# separate class method
@classmethod
def display_company_name(cls):
    print(f"Distplay {cls.bank_name}")

In [ ]:
class Bank:
    def __init__(self,ac_no,bal):
        self.__Account_number=ac_no # i want to make the private __ by using 2 undersore
        self.balance=bal   # _ for protect
        # to access the private attribute using getter and setter
    def get_account_no(self):
        print(self.__Account_number)
        
# create the class object
bank=Bank(122342,54000)
bank.get_account_no()

#####  create the class Employee take 3 arguments id ,salary and pf money. get the private attributes. salary>10000, pf money>1000. create the method to display the employee details and calculate the total salary. create the object of the class and call the methods

In [ ]:
class Employee:
    def __init__(self, id, salary, pf_money):
        self.id = id
        self.__salary = salary
        self.__pf_money = pf_money
    # Getter Methods
    def get_salary(self):
        return self.__salary
    def get_pf_money(self):
        return self.__pf_money
    # Setter Methods
    def set_salary(self, new_salary):
        if new_salary > 10000:
            self.__salary = new_salary
        else:
            print("Salary must be greater than 10000")
    def set_pf(self, new_pf):
        if new_pf > 1000:
            self.__pf_money = new_pf
        else:
            print("PF money must be greater than 1000")
    # Display Employee Details
    def display(self):
        print("Employee ID :", self.id)
        print("Salary      :", self.__salary)
        print("PF Money    :", self.__pf_money)
    # Calculate Total Salary
    def total_salary(self):
        total = self.__salary + self.__pf_money
        print("Total Salary =", total)
# Object Creation
emp = Employee(34, 100000, 5000)
# Display Details
emp.display()
# Total Salary
emp.total_salary()
# Update Salary
emp.set_salary(300000)
# Update PF
emp.set_pf(8000)
print("\nAfter Updating")
emp.display()
emp.total_salary()

#### Encapsulation

In [ ]:
# Encapsulation means wrapping data and mathods togeher inside a class and controlling direct access to the data
# Suppose we have mobile phone you press power button the phone is turns on You don't know what is happening inside the phone.
# The internal process is hidden. This is called Encapsulation.

In [ ]:
class Bank_account:
    #constructor:
    def __init__(self,owner,bal):
        # create attributes
        self.owner_name=owner
        self.balance=bal
    def display_bank_details(self):
        print("Owner Name=", self.owner_name)
        print("Bank balance=",self.balance)
# create object
bank1=Bank_account("Sumit",200)
# bank1.display_bank_details()
bank1.balance

In [ ]:
class Bank_account:
    #constructor:
    def __init__(self,owner,bal):
        # create attributes
        self.owner_name=owner
        self.__balance=int(bal) # private
    
    # getter we use to access the private method
    def get_balance(self):
        return self.__balance
    # setter always apply condtion is used when we want update data
    def set_deposit(self,amt):
        if amt>0:
            self.__balance+=amt
        else:
            return ("Invalid amount")
        return self.__balance
    def display_bank_details(self):
        print("Owner Name=", self.owner_name)
        print("Bank balance=",self.balance)
# create object
bank1=Bank_account("Sumit",200)
# bank1._Bank_account__balance
bank1.get_balance()
# bank1.set_deposit("fas") error
# bank1.set_deposit(-400) invalid amount
bank1.set_deposit(1600)

In [ ]:
# 
from abc import ABC, abstractmethod
class Class_name(ABC):
    # abstract method
    @abstractmethod
    def sound(self):
        pass

In [ ]:
# without abstaction
class Cat:
    def sound(self):
        print("Meowwww")
class dog:
    def sound(self):
        print("Bhauuu")
class cow:
    def sount(self):
        print("hamba")

In [ ]:
# with abstraction   # we cnnot create the object of abstract class
class Animals(ABC):
    @abstractmethod
    def sound(self):
        pass
# child Class 
class Cat(Animals):
    def sound(self):
        print("Mewooo")
# child Class 

class Dog(Animals):
    def sound(self):
        print("Bhauu")
#child Class 
       
class Cow(Animals):
    def sound(self):
        print("hamba")
cat=Cat()
cat.sound()

In [ ]:
# food management 
class Food(ABC):
    #constructor
    def __init__(self,f_name,f_price):
        self.__Food_name=f_name
        self.__Food_price=f_price
    # getter
    def get_food_name(self):
        return self.__Food_name
    def get_food_price(self):
        return self.__Food_price
    # abstract method
    @abstractmethod
    def prepare(self):
        pass
    # abstract method
    @abstractmethod
    def deliver(self):
        pass
    def display_all_details(self):
        print(f"Food Name:{self.__Food_name}")
        print(f"Food Name:{self.__Food_price}")
        self.prepare()
        self.deliver()

# child class
class Pizza(Food):
    def prepare(self):
        print("Pizza is prepared")
    def deliver(self):
        print("Pizza is deliver")

class Burger(Food):
    def prepare(self):
        print("Burger is prepared")
    def deliver(self):
        print("Burger is deliver")

# create the class object
pizza=Pizza("Pizaa",500)
pizza.get_food_name()
pizza.get_food_price()
burger=Burger("Burger",900)
burger.get_food_name()
burger.get_food_price()
pizza.display_all_details()
print("*"*80)
burger.display_all_details()

In [ ]:
# talke the parent :company
# take two argument name,role
#take peivate
#make two abstract method 1 works ,2 salary
# create two child class worker ,manager ,diplaay all info


# company management 
class Company(ABC):
    #constructor
    def __init__(self,name,role):
        self.__name=name
        self.__role=role
    # getter
    def get_name(self):
        return self.__name
    def get_role(self):
        return self.__role
    # abstract method
    @abstractmethod
    def work(self):
        pass
    # abstract method
    @abstractmethod
    def salary(self):
        pass
    def display_all_details(self):
        print(f"Name:{self.__name}")
        print(f"Role:{self.__role}")
        self.work()
        self.salary()

# child class
class Worker(Company):
    def work(self):
        print("Worker ")
    def salary(self):
        print("salary=",30000)

class Manager(Company):
    def work(self):
        print("Manager")
    def salary(self):
        print("salary",78000)

# create the class object
worker1=Worker("Amit","data scientist")
worker1.get_name()
worker1.get_role()
manager1=Manager("Sameer","data scientist")
manager1.get_name()
manager1.get_role()
worker1.display_all_details()
print("*"*80)
manager1.display_all_details()

In [ ]:
#payments :
from abc import ABC,abstractmethod
class Payment(ABC):
    # consturctor:
    def __init__(self,owner,amount):
        self.__owner_name=owner
        self.__amount=amount  # private
        
    # getter :get the owner name:
    def get_owner(self):
        return f"Owner Name:{self.__owner_name}"
    # getter :get the Amount:
    def get_amount(self):
        return f"Amount::{self.__amount}"

    # setter :
    def set_amount(self,amount):
        if amt >0:
            self.__amount += amt
            return f"Amount Updated :{self.__amount}"
        else :
            print("Please enter  the amount more than zero")
    @abstractmethod
    def pay(self):
        pass
    def recipt(self):
        return (f"Owner Name:{self.__owner_name}\nAmount:{self.__amount}")
        
#child class
class Credit_card(Payment):
    def __init__(self,owner,amount,cre_no):
        super().__init__(owner,amount)
        self.__cre_no=cre_no
    def pay(self):
        print("Credit card  detials")
        print("Credit card no=",self.__cre_no)
        self.recipt()

class Debit_card(Payment):
    def __init__(self,owner,amount,dbe_no):
        super().__init__(owner,amount)
        self.__dbe_no=dbe_no
    def pay(self):
        print("Debit card  detials")
        print("Debit card no=",self.__dbe_no)
        print(self.receipt())
        
class Upi(Payment):
    def __init__(self,owner,amount,upi_id):
        super().__init__(owner,amount)
        self.__upi_id=upi_id
    def pay(self):
        print("Upi  detials")
        print("UPI ID=",self.__upi_id)
        self.recipt()  
# create ClASS Object:
credit=Credit_card("Piyush Wani",1000,12345)
debit=Debit_card=("Sumit",2500,96385)
upi=Upi("Sunny Bhai",5000,75395)

#call The Methods and attributes:
print(credit.get_owner())
print(credit.get_amount())
print(credit.recipt())
print(credit.pay())

In [ ]:
#payments :
from abc import ABC,abstractmethod
class Agent(ABC):
    # consturctor:
    def __init__(self,name,agent_api_key):
        self.name=name
        self.__agent_api_key=agent_api_key  # private
    # getter :to get api key
    def get_agent(self):
        return f"Agent_key:{self.__agent_api_key}"

    @abstractmethod
    def LLM_Model(self):
        pass

    def agent_info(self):
        return f"Agent name:{self.name} \nAgent_api_key={self.__agent_api_key}"
        
#child class
class Flight_book(Agent):
    def __init__(self,name,agent_api_key,agent_role):
        super().__init__(name,agent_api_key)
        self.agent_role=agent_role
    def LLM_Model(self):
        return "Open AI LLM Model"
    def display_all_details(self):
        print(f"Agent Role:{self.agent_role}")
        print(self.agent_info())
        print(self.LLM_Model())

class Hotel_book(Agent):
    def __init__(self,name,agent_api_key,agent_role):
        super().__init__(name,agent_api_key)
        self.hotel_agent_role=agent_role
    def LLM_Model(self):
        return "Open AI LLM Model"
    def display_all_details(self):
        print(f"Agent Role:{self.hotel_agent_role}")
        print(self.agent_info())
        print(self.LLM_Model())   
flight=Flight_book("Flight_agent",9890,"Book the flight")
hotel=Hotel_book("Hotel_agent",988,"Book the hotel")
print(flight.agent_info())
flight.display_all_details()

In [ ]:
from abc import ABC, abstractmethod

# Abstract Class
class Agent(ABC):

    def __init__(self, agent_name, api_key, role):
        self.agent_name = agent_name
        self.__api_key = api_key      # Private Attribute
        self.role = role

    # Getter
    def get_api_key(self):
        return self.__api_key

    # Setter
    def set_api_key(self, api_key):
        self.__api_key = api_key

    # Abstract Method
    @abstractmethod
    def perform_task(self):
        pass


# Child Class 1
class FlightBookingAgent(Agent):

    def __init__(self, agent_name, api_key, role, airline):
        super().__init__(agent_name, api_key, role)
        self.airline = airline

    def perform_task(self):
        print("\n----- Flight Booking Agent -----")
        print("Agent Name :", self.agent_name)
        print("Role :", self.role)
        print("Airline :", self.airline)
        print("Task : Flight Booked Successfully")


# Child Class 2
class HotelBookingAgent(Agent):

    def __init__(self, agent_name, api_key, role, hotel_name):
        super().__init__(agent_name, api_key, role)
        self.hotel_name = hotel_name

    def perform_task(self):
        print("\n----- Hotel Booking Agent -----")
        print("Agent Name :", self.agent_name)
        print("Role :", self.role)
        print("Hotel :", self.hotel_name)
        print("Task : Hotel Booked Successfully")


# Objects
flight = FlightBookingAgent("SkyAgent","API12345","Flight Booking","IndiGo")

hotel = HotelBookingAgent("StayAgent","API67890","Hotel Booking","Taj Hotel")

flight.perform_task()
hotel.perform_task()

print("\nPrivate API Key:", flight.get_api_key())

flight.set_api_key("NEWAPI999")
print("Updated API Key:", flight.get_api_key())

In [ ]:
# Grand Parent Class
class Person:
    def __init__(self, name, age):
        self.Name = name
        self.Age = age
    def get_name(self):
        return self.Name
    def get_age(self):
        return self.Age
    def set_age(self, age):
        if 20 <= age <= 60:
            self.Age = age
            print("Age updated successfully.")
        else:
            print("Age must be between 20 and 60.")
    def person_info(self):
        print("Name :", self.Name)
        print("Age  :", self.Age)
class Employee(Person):
    def __init__(self, name, age, salary, company):
        super().__init__(name, age)
        self.Employee_salary = salary
        self.Company_name = company
    def get_salary(self):
        return self.Employee_salary

    def get_company(self):
        return self.Company_name
    def set_salary(self, sal):
        if sal <= (20 / 100) * self.Employee_salary:
            self.Employee_salary += sal
            print("Salary updated successfully.")
        else:
            print("Increment should be less than or equal to 20%.")
    def employee_info(self):
        self.person_info()
        print("Company :", self.Company_name)
        print("Salary  :", self.Employee_salary)

class Manager(Employee):

    def __init__(self, name, age, salary, company, team_size, bonus):
        super().__init__(name, age, salary, company)
        self.Team_size = team_size
        self.Bonus = bonus

    def get_team_size(self):
        return self.Team_size

    def get_bonus(self):
        return self.Bonus
    def set_team(self, new_team):
        if 5 <= new_team<=10:
            self.Team_size = new_team
            print("Team size updated.")
        else:
            print("Team size must be between 5 and 10.")

    def set_bonus(self, new_bonus):
        if new_bonus <= (10 / 100) * self.Employee_salary:
            self.Bonus = new_bonus
            print("Bonus updated.")
        else:
            print("Bonus should not exceed 10% of salary.")

    # Display
    def display_all_info(self):
        self.employee_info()
        print("Team Size :", self.Team_size)
        print("Bonus     :", self.Bonus)
# Create Object
manager1 = Manager("Sameer", 25, 50000, "Microsoft", 8, 4000)

# Display Information
manager1.display_all_info()

print()

# Getters
print(manager1.get_name())
print(manager1.get_age())
print(manager1.get_salary())
print(manager1.get_company())
print(manager1.get_team_size())
print(manager1.get_bonus())

print()

# Setters
manager1.set_age(30)
manager1.set_salary(5000)
manager1.set_team(9)
manager1.set_bonus(3000)

print()

# Display Updated Information
manager1.display_all_info()

In [ ]:
# Exception handling
list1=[8,9,0]
list1[9]
# index error

In [ ]:
#Syntax
try:
    # block of code
except Exceptiontype:
    # error message

In [ ]:
try:
    a=2.3
    b="Sumit"
    c=a+b
    print(c)
except TypeError:
    print("string type data can not add with numeric type data")

In [ ]:
try:
    print(10 / 0)

except ZeroDivisionError:
    print("Division by zero is not allowed.")

In [ ]:
try:
    list1=[4,6,7]
    list1[8]
except IndexError:
    print("Index Error")

In [ ]:
try:
    a="sumit"
    b=90
    c=A+b
    print(c) #Exception contain all error
except Exception as e: # e is used to show original system message
    print(e)

In [ ]:
try:
    a="sumit"
    b=90
    c=a+b
    print(c)
except (NameError,TypeError) as e: # multi exception
    print(e)

In [ ]:
try:
    a="sumit"
    b=90
    c=A+b
    print(c)
except Exception : 
    print("Kuch problem hai")

In [ ]:
try:
    user_id=input("Enter a user Id")
    password=input("Enter a password")
    if user_id=="Sumit@4952" and password=="admin":
        print("user name and password is matched")
except Exception as e:
    print(e)
else:
    print("login sucessfully")

In [ ]:
try:
    a = 10
    b = 9
    print(a / b)

except:
    print("Error")

else:
    print("Everything is correct.")

In [ ]:

try:
    print(10 / 2)

except:
    print("Error")

finally:
    print("Program Finished")

In [ ]:
try:
    num = int(input("Enter Number: "))
    print(100 / num)

except ZeroDivisionError:
    print("Cannot divide by zero.")

except ValueError:
    print("Please enter numbers only.")

else:
    print("Calculation completed successfully.")

finally:
    print("Thank You")

In [ ]:
try :
    a=20
    b="sumit"
    c=a+b
except Exception as e:
    print(e)
else:
    print(c)
finally:
    print("All process Done")

In [ ]:
# create the funtion using try except
# try
#take value from user side 
#create funtion even or odd
#except :
#error message
#else call the function
# finally print the message program executed
num=int(input("Enter a number:"))
try:
    def even_odd(num):
        if num%2==0:
            print("Even no ",num)
        else:
            print("Odd no ",num)
except Exception as e:
    print(e)
else:
    even_odd(num)
finally:
    print("Execution Sucessfully")

In [ ]:
from abc import ABC,abstractmethod
class InsufficientBalanceError(Exception):
    pass
class InvalidAmountError(Exception):
    pass
class AccountNotFoundError(Exception):
    pass
class DailyLimitExceededError(Exception):
    pass
class Account(ABC):
    total_account=0
    def __init__(self,name,balance):
        self.name=name
        self.balance=balance
        Account.total_account+=1
    @abstractmethod
    def deposit(self,amount):
        pass
    @abstractmethod
    def withdraw(self,amount):
        pass
    @abstractmethod
    def get_balance(self):
        pass
    def show_account_info(self):
        print("Account Holder:",self.name)
        print("Account No:",self.account_no)
        print("Balance:",self.get_balance())
    @classmethod
    def show_total_accounts(cls):
        print("Total Accounts Created:",cls.total_account)
class SavingsAccount(Account):
    daily_limit=25000
    minimum_balance=1000
    interest_rate=4
    def __init__(self,name,balance):
        super().__init__(name,balance)
        self.__account_no=1000+Account.total_account
        self.__daily_withdraw=0
    def get_balance(self):
        return self._balance
    def set_balance(self,amount):
        if amount<0:
            raise InvalidAmountError("Invalid Balance")
        self._balance=amount
    @property
    def account_no(self):
        return self.__account_no
    def deposit(self,amount):
        if amount<=0:
            raise InvalidAmountError("Deposit amount must be greater than zero")
        self.set_balance(self.get_balance()+amount)
        print("Deposit Successful")
    def withdraw(self,amount):
        if amount<=0:
            raise InvalidAmountError("Withdrawal amount must be positive")
        if self.__daily_withdraw+amount>SavingAccount.daily_limit:
            raise InsufficientBalaneError("Daily withdrawal limit crossed")
        remaining_balance=self.get_balance()-amount
        if remaining_balance<SavingsAccount.minimus_balance:
            raise InsufficientBalanceError("Minimum balance should be maintained")
        self.set_balance(remaining_balance)
        self.__daily_withdraw+=amount
        print("Withdrawal Successful")
class CurrentAccount(Account):
    overdraft_limit=10000
    def __init__(self,name,balance):
        super().__init__(name,balance)
        self.__account_no=1000+Account.total_account
    def get_balance(self):
        return self._balance
    def set_balance(self,amount):
        self._balance=amount
    @property
    def account_no(self):
        return self.__account_no
    def deposit(self,amount):
        if amount<=0:
            raise InvalidAmountError("Deposit amount must be positive")
        self.set_balance(self.get_balance()+amount)
        print("Deposit Successful")
    def withdraw(self,amount):
        if amount<=0:
            raise InvalidAmountError("Invalid withdrawal amount")
        allowed_amount=self.get_balance()+CurrentAccount.overdraft_limit
        if amount>allowed_amount:
            raise InsufficientBalanceError("Overdraft limit crossed")
        self.set_balance(self.get_balance()-amount)
        print("Withdrawal Successful")
accounts={}
def create_account():
    try:
        print("\n1. Savings Account")
        print("2. Current Account")
        choice=int(input("Choose Account Type:"))
        name=input("Enter a Name:")
        balance=float(input("Enter a Initial Balance:"))
        if choice==1:
            if balance<1000:
                raise InvalidAmountError("Savings account requires minimum rupees 1000")
            acc=SavingsAccount(name,balance)
        elif choice==2:
            acc=CurrentAccount(name,balance)
        else:
            print("Invalid choice")
            return
        accounts[acc.account_no]=acc
        print("\nAccount Created Successfully")
        print("Account Number:",acc.account_no)
    except Exception as e:
        print("Error:",e)
    finally:
        print("Account creation process completed")
def find_account():
    acc_no=int(input("Enter Account Number: "))
    if acc_no not in accounts:
        raise AccountNotFoundError("Account does not exist")
    raise accounts[acc_no]
def deposit_money():
    try:
        acc=find_account()
        amount=float(input("Enter Deposit Amount: "))
        acc.deposit(amount)
    except Exception as e:
        print("Error:",e)
    finally:
        print("Transaction completed")
def withdraw_money():
    try:
        acc=find_account()
        amount=float(input("Enter withdrawal Amount:"))
        acc.withdraw(amount)
    except Exception as e:
        print("Error:",e)
    finally:
        print("Transaction completed")
def check_balance():
    try:
        acc=find_account()
        print("Balance:",acc.get_balance())
    except Exception as e:
        print("Error:",e)
def show_info():
    try:
        acc=find_account()
        acc.show_account_info()
    except Exception as e:
        print("Error:",e)

while True:
    print("\n========== BANK MENU ==========")
    print("1. Create Account")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Check Balance")
    print("5. Show Account Info")
    print("6. Show Total Accounts")
    print("7. Exit")
    try:
        choice=int(input("Enter Choice: "))

        if choice==1:
            create_account()
        elif choice==2:
            deposit_money()
        elif choice==3:
            withdraw_money()
        elif choice==4:
            check_balance()
        elif choice==5:
            show_info()
        elif choice==6:
            Account.show_total_accounts()
        elif choice==7:
            print("Thank You For Banking!")
            break
        else:
            print("Invalid Choice")

    except Exception as e:
        print("Error:",e)

In [ ]:
class Count:

    def __init__(self):
        self.num = 1

    def __iter__(self):
        return self

    def __next__(self):
        if self.num <= 5:
            value = self.num
            self.num += 1
            return value
        else:
            raise StopIteration
obj=Count()
for i in obj:
    print(i)

In [6]:
dicts = {
    "names": ["Sameer", "Ram", "Rohit"],
    "age": [22, 23, 21],
    "city": ["Hyderabad", "Pune", "Mumbai"]
}
print(dicts)

{'names': ['Sameer', 'Ram', 'Rohit'], 'age': [22, 23, 21], 'city': ['Hyderabad', 'Pune', 'Mumbai']}

In [7]:
# method 1=DataFrame : convert the dict/json/array
import pandas as pd
df=pd.DataFrame(dicts)
print(df)

    names  age       city
0  Sameer   22  Hyderabad
1     Ram   23       Pune
2   Rohit   21     Mumbai

In [8]:
list1=[5,5,6,7,7]
df=pd.DataFrame(list1)
print(df)
print()
df=pd.DataFrame(list1,columns=["numbers"])
print(df)

   0
0  5
1  5
2  6
3  7
4  7

   numbers
0        5
1        5
2        6
3        7
4        7

In [9]:
# method 2 : read_csv:load the dataset
df=pd.read_csv("C:\\Users\\hp\\Downloads\\dataset.csv")
df=pd.read_csv("C:/Users/hp/Downloads/dataset.csv")
df=pd.read_csv("C:/Users/hp/Downloads/dataset.csv",encoding="latin1")

In [10]:
df

,ï»¿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [11]:

# head top 5 rows
df.head()

,ï»¿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
# tail():

In [12]:
# sample(): to display the random row or rows
df.sample()
df.sample(10)

,ï»¿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
235,51,1,0,140,299,0,1,173,1,1.6,2,0,3,0
63,41,1,1,135,203,0,1,132,0,0.0,1,0,1,1
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3,0
255,45,1,0,142,309,0,0,147,1,0.0,1,3,3,0
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2,1
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
185,44,1,0,112,290,0,0,153,0,0.0,2,1,2,0
241,59,0,0,174,249,0,1,143,1,0.0,1,0,2,0
95,53,1,0,142,226,0,0,111,1,0.0,2,0,3,1

In [13]:
# shape():check the size of data
df.shape

(303, 14)

In [14]:
# info :check the information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ï»¿age    303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
# columns : check the columns name of the datasets
df.columns

Index(['ï»¿age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [17]:
# data type : chect all columns of datatype
df.dtypes

ï»¿age        int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [18]:
# isnull : check the missing vlaue  in data
df.isnull()

,ï»¿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
df.isnull().sum()

ï»¿age      0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [20]:
# isna:
df.isna()

,ï»¿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
# select_dtype:select the single column
df['target']
Target=df['target']
df['target']

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [22]:
# Select Multiple column
df[["age","sex"]]

KeyError: "['age'] not in index"

In [ ]:
# select_dtype:select the specific type of columns
df.select_dtypes(include=["int"]).columns

In [ ]:
# all information of data
df.describe()

In [23]:
# drop : to drop the column
df1=

df.drop("exang",axis=1) # drop that coloumn for temporaily

SyntaxError: invalid syntax (1551999653.py, line 2)

In [24]:
#duplicated():to check the row
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [25]:
df.duplicated().sum()

np.int64(1)

In [28]:
# drop_duplicates()
df.drop_duplicates(inplace=True)

In [29]:
df.duplicated().sum()

np.int64(0)

In [32]:
# value_count():
df["target"].value_counts()

target
1    164
0    138
Name: count, dtype: int64

In [33]:
df["target"].value_counts(dropna=True)

target
1    164
0    138
Name: count, dtype: int64

In [ ]:
import turtle
import math
import random

screen = turtle.Screen()
screen.bgcolor("black")

t = turtle.Turtle()
t.speed(0)
t.hideturtle()
t.pensize(1)

colors = [
    "red",
    "blue",
    "lime",
    "yellow",
    "cyan",
    "magenta",
    "orange",
    "pink"
]

for i in range(120):
    t.penup()
    t.goto(0, 40)

    angle = i * (math.pi * 2) / 120

    x = 16 * (math.sin(angle) ** 3)

    y = (
        13 * math.cos(angle)
        - 5 * math.cos(2 * angle)
        - 2 * math.cos(3 * angle)
        - math.cos(4 * angle)
    ) * 15

    c = random.choice(colors)
    t.color(c)

    t.pendown()
    t.goto(x, y)

    for _ in range(8):
        t.forward(6)
        t.backward(6)
        t.right(45)

turtle.done()

In [1]:
marks = [75, 82, 68, 91, 88]

for i, mark in enumerate(marks):
    print("Student", i + 1, "Marks:", mark)

Student 1 Marks: 75
Student 2 Marks: 82
Student 3 Marks: 68
Student 4 Marks: 91
Student 5 Marks: 88