In [19]:
# Import Pandas using pd.
# Create a Series with numbers 10, 20, 30, 40.
# Create a Series using your friends' names.
# Create a Series using a dictionary of student marks.
# Create a Series with custom indexes (Math, Science, English).
# Create a DataFrame with columns Name, Age, and City.
# Print the shape of the DataFrame.
# Print the size of the DataFrame.
# Print the number of dimensions (ndim).
# Print the column names and data types using columns and dtypes.
import pandas as pd
data=pd.Series([10,20,30,40])
print(data)
#2
print()
names=pd.Series(["Sameer","Sumit","Sanjay"])
print(names)
#3
print()
students={"Sameer":90,"Sumit":80,"Sanjay":40}
data=pd.Series(students)
print(data)
#4
print()
marks=[30,40,60]
data=pd.Series(marks,index=["Math","Science","English"])
print(data)
#6
print()
student={
    "Name":["Sameer","Ram","Rohit"],
    "Age":[22,23,21],
    "City":["Hyderabad","Pune","Mumbai"]}
df=pd.DataFrame(student)
print(df)
print()
#7
print(df.shape)
#8
print()
print(df.size)
#9
print()
print(df.ndim)
#10
print()
print(df.dtypes)

0    10
1    20
2    30
3    40
dtype: int64

0    Sameer
1     Sumit
2    Sanjay
dtype: object

Sameer    90
Sumit     80
Sanjay    40
dtype: int64

Math       30
Science    40
English    60
dtype: int64

     Name  Age       City
0  Sameer   22  Hyderabad
1     Ram   23       Pune
2   Rohit   21     Mumbai

(3, 3)

9

2

Name    object
Age      int64
City    object
dtype: object

# module1

In [30]:
# Import the Pandas library.
# Read a file named students.csv.
# Display the first 5 rows.
# Display the first 8 rows.
# Display the last 5 rows.
# Display the last 10 rows.
# Show 3 random rows.
# Show 7 random rows.
# Find the number of rows and columns using shape.
# Print only the number of rows.
# Print only the number of columns.
# Display the dataset summary using info().
# Print all column names.
# Convert the column names into a Python list.
# Display the data type of each column.
#1
import pandas as pd
#2
print()
data=pd.read_csv("C:\\Users\\hp\\Downloads\\students.csv ")
print(data)
#3
print()
print(data.head())
#4
print()
print(data.head(8))
#5
print()
print(data.tail())
#6
print()
print(data.tail(10))
#7
print()
print(data.sample(3))
#8
print()
print(data.sample(7))
#9
print()
print(data.shape)
#10
print()
print(data.shape[0])
#11
print()
print(data.shape[1])
#12
print()
print(data.info())
#13
print()
print(data.columns)
#14
print()
print(list(data.columns))
#15
print()
print(list(data.dtypes))

    Roll    Name  Age  Gender       City  Marks
0    101  Sameer   22    Male  Hyderabad     89
1    102   Rahul   21    Male       Pune     76
2    103   Priya   20  Female     Mumbai     95
3    104    Amit   23    Male      Delhi     80
4    105   Sneha   22  Female     Nagpur     90
5    106   Rohit   21    Male       Pune     78
6    107  Anjali   20  Female  Hyderabad     85
7    108   Karan   23    Male      Delhi     67
8    109   Pooja   22  Female     Mumbai     91
9    110   Vikas   21    Male     Nagpur     74
10   111    Neha   20  Female       Pune     88
11   112   Arjun   22    Male  Hyderabad     82
12   113  Kavita   21  Female      Delhi     79
13   114  Sachin   23    Male     Mumbai     86
14   115    Riya   20  Female       Pune     93
15   116   Mohan   22    Male     Nagpur     72
16   117  Simran   21  Female  Hyderabad     84
17   118  Deepak   23    Male      Delhi     69
18   119   Meena   22  Female     Mumbai     87
19   120   Akash   21    Male       Pune     75

   Roll    Name  Age  Gender       City  Marks
0   101  Sameer   22    Male  Hyderabad     89
1   102   Rahul   21    Male       Pune     76
2   103   Priya   20  Female     Mumbai     95
3   104    Amit   23    Male      Delhi     80
4   105   Sneha   22  Female     Nagpur     90

   Roll    Name  Age  Gender       City  Marks
0   101  Sameer   22    Male  Hyderabad     89
1   102   Rahul   21    Male       Pune     76
2   103   Priya   20  Female     Mumbai     95
3   104    Amit   23    Male      Delhi     80
4   105   Sneha   22  Female     Nagpur     90
5   106   Rohit   21    Male       Pune     78
6   107  Anjali   20  Female  Hyderabad     85
7   108   Karan   23    Male      Delhi     67

    Roll    Name  Age  Gender       City  Marks
15   116   Mohan   22    Male     Nagpur     72
16   117  Simran   21  Female  Hyderabad     84
17   118  Deepak   23    Male      Delhi     69
18   119   Meena   22  Female     Mumbai     87
19   120   Akash   21    Male       Pune     75

    Roll    Name  Age  Gender       City  Marks
10   111    Neha   20  Female       Pune     88
11   112   Arjun   22    Male  Hyderabad     82
12   113  Kavita   21  Female      Delhi     79
13   114  Sachin   23    Male     Mumbai     86
14   115    Riya   20  Female       Pune     93
15   116   Mohan   22    Male     Nagpur     72
16   117  Simran   21  Female  Hyderabad     84
17   118  Deepak   23    Male      Delhi     69
18   119   Meena   22  Female     Mumbai     87
19   120   Akash   21    Male       Pune     75

    Roll    Name  Age  Gender       City  Marks
14   115    Riya   20  Female       Pune     93
16   117  Simran   21  Female  Hyderabad     84
8    109   Pooja   22  Female     Mumbai     91

    Roll    Name  Age  Gender       City  Marks
0    101  Sameer   22    Male  Hyderabad     89
19   120   Akash   21    Male       Pune     75
9    110   Vikas   21    Male     Nagpur     74
7    108   Karan   23    Male      Delhi     67
12   113  Kavita   21  Female      Delhi     79
13   114  Sachin   23    Male     Mumbai     86
18   119   Meena   22  Female     Mumbai     87

(20, 6)

20

6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Roll    20 non-null     int64
 1   Name    20 non-null     object
 2   Age     20 non-null     int64
 3   Gender  20 non-null     object
 4   City    20 non-null     object
 5   Marks   20 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.1+ KB
None

Index(['Roll', 'Name', 'Age', 'Gender', 'City', 'Marks'], dtype='object')

['Roll', 'Name', 'Age', 'Gender', 'City', 'Marks']

[dtype('int64'), dtype('O'), dtype('int64'), dtype('O'), dtype('O'), dtype('int64')]

In [7]:
# module 2
import pandas as pd
#1
df=pd.read_csv("C:\\Users\\hp\\Downloads\\students2.csv")
# Read students.csv into a DataFrame.
# Check for missing values using isnull().
# Count missing values in each column.
# Use isna() to verify the result.
# Display only the Name column.
# Display the Name and Marks columns together.
# Show only numeric columns using select_dtypes(include="int").
# Show only text columns using select_dtypes(include="object").
# Display the statistical summary of numeric columns using describe().
# Display the summary of text columns using describe(include="object").
# Check for duplicate rows.
# Count the number of duplicate rows.
# Remove duplicate rows and save the result.
# Count the number of students in each city using value_counts().
# Count the number of male and female students using value_counts
print(df)
#2
print()
print(df.isnull())
#3
print()
print(df.isnull().sum())
#4
print()
print(df.isna())
#5
print()
print(df["Name"])
#6
print()
print(df[["Name","Marks"]])
#7
print()
print(df.select_dtypes(include="int"))
#8
print()
print(df.select_dtypes(include="object"))
#9
print()
print(df.describe())
#10
print()
print(df.describe(include="object"))
#11
print()
print(df.duplicated())
#12
print()
print(df.duplicated().sum())
#13
print()
remov=df.drop_duplicates()
print(remov)
#14
print()
print(df["City"].value_counts())
#15
print()
print(df["Gender"].value_counts())

    Roll      Name   Age  Gender       City  Marks
0    101    Sameer  22.0    Male  Hyderabad   89.0
1    102     Rahul  21.0    Male       Pune   76.0
2    103     Priya  20.0  Female     Mumbai   95.0
3    104      Amit  23.0    Male      Delhi   80.0
4    105     Sneha  22.0  Female     Nagpur   90.0
5    106     Rohit  21.0    Male       Pune   78.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
7    108     Karan  23.0    Male      Delhi   67.0
8    109     Pooja  22.0  Female     Mumbai   91.0
9    110     Vikas  21.0    Male     Nagpur   74.0
10   111      Neha  20.0  Female       Pune   88.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
12   113    Kavita  21.0  Female      Delhi   79.0
13   114    Sachin  23.0    Male     Mumbai   86.0
14   115      Riya  20.0  Female       Pune   93.0
15   116     Mohan  22.0    Male     Nagpur   72.0
16   117    Simran  21.0  Female  Hyderabad   84.0
17   118    Deepak  23.0    Male      Delhi   69.0
18   119     Meena  22.0  Female     Mumbai   87.0
19   120     Akash  21.0    Male       Pune   75.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
21   122    Nikita  22.0  Female     Mumbai   92.0
22   123     Sumit  21.0    Male       Pune   77.0
23   124     Aarti  23.0  Female      Delhi   83.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
25   126     Komal  20.0  Female  Hyderabad   89.0
26   127     Harsh  21.0    Male     Mumbai   85.0
27   128     Divya  22.0  Female       Pune   94.0
28   129     Nitin  23.0    Male      Delhi   71.0
29   130    Shreya  20.0  Female     Nagpur   90.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
31   132     Payal  22.0  Female     Mumbai   88.0
32   133     Sagar  23.0    Male       Pune   79.0
33   134     Tanvi  20.0  Female      Delhi   91.0
34   135    Manish  22.0    Male     Nagpur   73.0
35   136     Swati  21.0  Female  Hyderabad   84.0
36   137      Yash  23.0    Male     Mumbai   86.0
37   138   Pallavi  22.0  Female       Pune   93.0
38   139  Abhishek  20.0    Male      Delhi   68.0
39   140    Khushi  21.0  Female     Nagpur   90.0
40   141     Rahul  21.0    Male       Pune   76.0
41   142       NaN  22.0  Female     Mumbai   85.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
43   144      Amit   NaN    Male      Delhi   80.0
44   145     Sneha  22.0  Female        NaN   90.0
45   146     Rohit  21.0    Male       Pune    NaN
46   147    Anjali  20.0  Female  Hyderabad   85.0
47   148     Karan  23.0    Male      Delhi   67.0
48   149     Pooja  22.0  Female     Mumbai   91.0
49   150     Vikas  21.0    Male     Nagpur   74.0

     Roll   Name    Age  Gender   City  Marks
0   False  False  False   False  False  False
1   False  False  False   False  False  False
2   False  False  False   False  False  False
3   False  False  False   False  False  False
4   False  False  False   False  False  False
5   False  False  False   False  False  False
6   False  False  False   False  False  False
7   False  False  False   False  False  False
8   False  False  False   False  False  False
9   False  False  False   False  False  False
10  False  False  False   False  False  False
11  False  False  False   False  False  False
12  False  False  False   False  False  False
13  False  False  False   False  False  False
14  False  False  False   False  False  False
15  False  False  False   False  False  False
16  False  False  False   False  False  False
17  False  False  False   False  False  False
18  False  False  False   False  False  False
19  False  False  False   False  False  False
20  False  False  False   False  False  False
21  False  False  False   False  False  False
22  False  False  False   False  False  False
23  False  False  False   False  False  False
24  False  False  False   False  False  False
25  False  False  False   False  False  False
26  False  False  False   False  False  False
27  False  False  False   False  False  False
28  False  False  False   False  False  False
29  False  False  False   False  False  False
30  False  False  False   False  False  False
31  False  False  False   False  False  False
32  False  False  False   False  False  False
33  False  False  False   False  False  False
34  False  False  False   False  False  False
35  False  False  False   False  False  False
36  False  False  False   False  False  False
37  False  False  False   False  False  False
38  False  False  False   False  False  False
39  False  False  False   False  False  False
40  False  False  False   False  False  False
41  False   True  False   False  False  False
42  False  False  False   False  False  False
43  False  False   True   False  False  False
44  False  False  False   False   True  False
45  False  False  False   False  False   True
46  False  False  False   False  False  False
47  False  False  False   False  False  False
48  False  False  False   False  False  False
49  False  False  False   False  False  False

Roll      0
Name      1
Age       1
Gender    0
City      1
Marks     1
dtype: int64

     Roll   Name    Age  Gender   City  Marks
0   False  False  False   False  False  False
1   False  False  False   False  False  False
2   False  False  False   False  False  False
3   False  False  False   False  False  False
4   False  False  False   False  False  False
5   False  False  False   False  False  False
6   False  False  False   False  False  False
7   False  False  False   False  False  False
8   False  False  False   False  False  False
9   False  False  False   False  False  False
10  False  False  False   False  False  False
11  False  False  False   False  False  False
12  False  False  False   False  False  False
13  False  False  False   False  False  False
14  False  False  False   False  False  False
15  False  False  False   False  False  False
16  False  False  False   False  False  False
17  False  False  False   False  False  False
18  False  False  False   False  False  False
19  False  False  False   False  False  False
20  False  False  False   False  False  False
21  False  False  False   False  False  False
22  False  False  False   False  False  False
23  False  False  False   False  False  False
24  False  False  False   False  False  False
25  False  False  False   False  False  False
26  False  False  False   False  False  False
27  False  False  False   False  False  False
28  False  False  False   False  False  False
29  False  False  False   False  False  False
30  False  False  False   False  False  False
31  False  False  False   False  False  False
32  False  False  False   False  False  False
33  False  False  False   False  False  False
34  False  False  False   False  False  False
35  False  False  False   False  False  False
36  False  False  False   False  False  False
37  False  False  False   False  False  False
38  False  False  False   False  False  False
39  False  False  False   False  False  False
40  False  False  False   False  False  False
41  False   True  False   False  False  False
42  False  False  False   False  False  False
43  False  False   True   False  False  False
44  False  False  False   False   True  False
45  False  False  False   False  False   True
46  False  False  False   False  False  False
47  False  False  False   False  False  False
48  False  False  False   False  False  False
49  False  False  False   False  False  False

0       Sameer
1        Rahul
2        Priya
3         Amit
4        Sneha
5        Rohit
6       Anjali
7        Karan
8        Pooja
9        Vikas
10        Neha
11       Arjun
12      Kavita
13      Sachin
14        Riya
15       Mohan
16      Simran
17      Deepak
18       Meena
19       Akash
20        Ajay
21      Nikita
22       Sumit
23       Aarti
24      Ramesh
25       Komal
26       Harsh
27       Divya
28       Nitin
29      Shreya
30       Vinay
31       Payal
32       Sagar
33       Tanvi
34      Manish
35       Swati
36        Yash
37     Pallavi
38    Abhishek
39      Khushi
40       Rahul
41         NaN
42      Sameer
43        Amit
44       Sneha
45       Rohit
46      Anjali
47       Karan
48       Pooja
49       Vikas
Name: Name, dtype: object

        Name  Marks
0     Sameer   89.0
1      Rahul   76.0
2      Priya   95.0
3       Amit   80.0
4      Sneha   90.0
5      Rohit   78.0
6     Anjali   85.0
7      Karan   67.0
8      Pooja   91.0
9      Vikas   74.0
10      Neha   88.0
11     Arjun   82.0
12    Kavita   79.0
13    Sachin   86.0
14      Riya   93.0
15     Mohan   72.0
16    Simran   84.0
17    Deepak   69.0
18     Meena   87.0
19     Akash   75.0
20      Ajay   81.0
21    Nikita   92.0
22     Sumit   77.0
23     Aarti   83.0
24    Ramesh   70.0
25     Komal   89.0
26     Harsh   85.0
27     Divya   94.0
28     Nitin   71.0
29    Shreya   90.0
30     Vinay   76.0
31     Payal   88.0
32     Sagar   79.0
33     Tanvi   91.0
34    Manish   73.0
35     Swati   84.0
36      Yash   86.0
37   Pallavi   93.0
38  Abhishek   68.0
39    Khushi   90.0
40     Rahul   76.0
41       NaN   85.0
42    Sameer   89.0
43      Amit   80.0
44     Sneha   90.0
45     Rohit    NaN
46    Anjali   85.0
47     Karan   67.0
48     Pooja   91.0
49     Vikas   74.0

    Roll
0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
10   111
11   112
12   113
13   114
14   115
15   116
16   117
17   118
18   119
19   120
20   121
21   122
22   123
23   124
24   125
25   126
26   127
27   128
28   129
29   130
30   131
31   132
32   133
33   134
34   135
35   136
36   137
37   138
38   139
39   140
40   141
41   142
42   143
43   144
44   145
45   146
46   147
47   148
48   149
49   150

        Name  Gender       City
0     Sameer    Male  Hyderabad
1      Rahul    Male       Pune
2      Priya  Female     Mumbai
3       Amit    Male      Delhi
4      Sneha  Female     Nagpur
5      Rohit    Male       Pune
6     Anjali  Female  Hyderabad
7      Karan    Male      Delhi
8      Pooja  Female     Mumbai
9      Vikas    Male     Nagpur
10      Neha  Female       Pune
11     Arjun    Male  Hyderabad
12    Kavita  Female      Delhi
13    Sachin    Male     Mumbai
14      Riya  Female       Pune
15     Mohan    Male     Nagpur
16    Simran  Female  Hyderabad
17    Deepak    Male      Delhi
18     Meena  Female     Mumbai
19     Akash    Male       Pune
20      Ajay    Male  Hyderabad
21    Nikita  Female     Mumbai
22     Sumit    Male       Pune
23     Aarti  Female      Delhi
24    Ramesh    Male     Nagpur
25     Komal  Female  Hyderabad
26     Harsh    Male     Mumbai
27     Divya  Female       Pune
28     Nitin    Male      Delhi
29    Shreya  Female     Nagpur
30     Vinay    Male  Hyderabad
31     Payal  Female     Mumbai
32     Sagar    Male       Pune
33     Tanvi  Female      Delhi
34    Manish    Male     Nagpur
35     Swati  Female  Hyderabad
36      Yash    Male     Mumbai
37   Pallavi  Female       Pune
38  Abhishek    Male      Delhi
39    Khushi  Female     Nagpur
40     Rahul    Male       Pune
41       NaN  Female     Mumbai
42    Sameer    Male  Hyderabad
43      Amit    Male      Delhi
44     Sneha  Female        NaN
45     Rohit    Male       Pune
46    Anjali  Female  Hyderabad
47     Karan    Male      Delhi
48     Pooja  Female     Mumbai
49     Vikas    Male     Nagpur

            Roll        Age      Marks
count   50.00000  49.000000  49.000000
mean   125.50000  21.489796  82.387755
std     14.57738   1.023117   8.012533
min    101.00000  20.000000  67.000000
25%    113.25000  21.000000  76.000000
50%    125.50000  22.000000  84.000000
75%    137.75000  22.000000  89.000000
max    150.00000  23.000000  95.000000

          Name Gender  City
count       49     50    49
unique      40      2     5
top     Sameer   Male  Pune
freq         2     27    11

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

0

    Roll      Name   Age  Gender       City  Marks
0    101    Sameer  22.0    Male  Hyderabad   89.0
1    102     Rahul  21.0    Male       Pune   76.0
2    103     Priya  20.0  Female     Mumbai   95.0
3    104      Amit  23.0    Male      Delhi   80.0
4    105     Sneha  22.0  Female     Nagpur   90.0
5    106     Rohit  21.0    Male       Pune   78.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
7    108     Karan  23.0    Male      Delhi   67.0
8    109     Pooja  22.0  Female     Mumbai   91.0
9    110     Vikas  21.0    Male     Nagpur   74.0
10   111      Neha  20.0  Female       Pune   88.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
12   113    Kavita  21.0  Female      Delhi   79.0
13   114    Sachin  23.0    Male     Mumbai   86.0
14   115      Riya  20.0  Female       Pune   93.0
15   116     Mohan  22.0    Male     Nagpur   72.0
16   117    Simran  21.0  Female  Hyderabad   84.0
17   118    Deepak  23.0    Male      Delhi   69.0
18   119     Meena  22.0  Female     Mumbai   87.0
19   120     Akash  21.0    Male       Pune   75.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
21   122    Nikita  22.0  Female     Mumbai   92.0
22   123     Sumit  21.0    Male       Pune   77.0
23   124     Aarti  23.0  Female      Delhi   83.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
25   126     Komal  20.0  Female  Hyderabad   89.0
26   127     Harsh  21.0    Male     Mumbai   85.0
27   128     Divya  22.0  Female       Pune   94.0
28   129     Nitin  23.0    Male      Delhi   71.0
29   130    Shreya  20.0  Female     Nagpur   90.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
31   132     Payal  22.0  Female     Mumbai   88.0
32   133     Sagar  23.0    Male       Pune   79.0
33   134     Tanvi  20.0  Female      Delhi   91.0
34   135    Manish  22.0    Male     Nagpur   73.0
35   136     Swati  21.0  Female  Hyderabad   84.0
36   137      Yash  23.0    Male     Mumbai   86.0
37   138   Pallavi  22.0  Female       Pune   93.0
38   139  Abhishek  20.0    Male      Delhi   68.0
39   140    Khushi  21.0  Female     Nagpur   90.0
40   141     Rahul  21.0    Male       Pune   76.0
41   142       NaN  22.0  Female     Mumbai   85.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
43   144      Amit   NaN    Male      Delhi   80.0
44   145     Sneha  22.0  Female        NaN   90.0
45   146     Rohit  21.0    Male       Pune    NaN
46   147    Anjali  20.0  Female  Hyderabad   85.0
47   148     Karan  23.0    Male      Delhi   67.0
48   149     Pooja  22.0  Female     Mumbai   91.0
49   150     Vikas  21.0    Male     Nagpur   74.0

City
Pune         11
Hyderabad    10
Mumbai       10
Delhi        10
Nagpur        8
Name: count, dtype: int64

Gender
Male      27
Female    23
Name: count, dtype: int64

In [4]:
# module 2
import pandas as pd
df=pd.read_csv("C:\\Users\\hp\\Downloads\\students2.csv")
df.head(15)

    Roll    Name   Age  Gender       City  Marks
0    101  Sameer  22.0    Male  Hyderabad   89.0
1    102   Rahul  21.0    Male       Pune   76.0
2    103   Priya  20.0  Female     Mumbai   95.0
3    104    Amit  23.0    Male      Delhi   80.0
4    105   Sneha  22.0  Female     Nagpur   90.0
5    106   Rohit  21.0    Male       Pune   78.0
6    107  Anjali  20.0  Female  Hyderabad   85.0
7    108   Karan  23.0    Male      Delhi   67.0
8    109   Pooja  22.0  Female     Mumbai   91.0
9    110   Vikas  21.0    Male     Nagpur   74.0
10   111    Neha  20.0  Female       Pune   88.0
11   112   Arjun  22.0    Male  Hyderabad   82.0
12   113  Kavita  21.0  Female      Delhi   79.0
13   114  Sachin  23.0    Male     Mumbai   86.0
14   115    Riya  20.0  Female       Pune   93.0

In [45]:
# Display the first 5 rows using loc[].
print(df.loc[0:4])
print()
# Display the first 5 rows using iloc[].
print(df.loc[0:5])
# Display only the Name column using loc[].
print()
print(df.loc[0:5,"Name"])
# Display the Name and Marks columns using iloc[].
print()
print(df.iloc[0:5,[1,5]])
# Show students with marks greater than 85.
print()
print(df[df["Marks"]>85])
# Show students with marks less than 75.
print()
print(df[df["Marks"]<75])
# Show students whose age is 22.
print()
print(df[df["Age"]==22])
# Show students whose city is Hyderabad.
print()
print(df[df["City"]=="Hyderabad"])
# Show students whose city is not Pune.
print()
print(df[df["City"]!="Pune"])
# Show students whose marks are greater than or equal to 90.
print()
print(df[df["Marks"]>=90])
# Show students whose marks are between 80 and 90.
print()
print(df[(df["Marks"]>=80 )& (df["Marks"]<=90)])
# Show students whose age is between 21 and 22.
print()
print(df[df["Age"].between(20,21)])
# Show students from Pune or Mumbai.
print()
print(df[(df["City"]=="Pune") | (df["City"]=="Mumbai")])
# Show students from Hyderabad and marks greater than 80.
print()
print(df[(df["City"]=="Hyderabad")&(df["Marks"]>80)])
# Show students whose city is Pune, Mumbai, or Delhi using isin().
print()
print(df[df["City"].isin(["Pune","Mumbai","Delhi"])])
# Show only the names of students whose marks are greater than 85 using loc[].
print()
print(df.loc[df["Marks"]>85,"Name"])
# Find all female students with marks above 85.
print()
print(df.loc[(df["Marks"] > 85) & (df["Gender"] == "Female"), "Name"])# Find all male students from Delhi.
# Show rows 10 to 20 using loc[]
print()
print(df.loc[10:20])
# Show rows 10 to 20 and only the Name and City columns using iloc[].
print()
print(df.iloc[10:21])

   Roll    Name   Age  Gender       City  Marks
0   101  Sameer  22.0    Male  Hyderabad   89.0
1   102   Rahul  21.0    Male       Pune   76.0
2   103   Priya  20.0  Female     Mumbai   95.0
3   104    Amit  23.0    Male      Delhi   80.0
4   105   Sneha  22.0  Female     Nagpur   90.0

   Roll    Name   Age  Gender       City  Marks
0   101  Sameer  22.0    Male  Hyderabad   89.0
1   102   Rahul  21.0    Male       Pune   76.0
2   103   Priya  20.0  Female     Mumbai   95.0
3   104    Amit  23.0    Male      Delhi   80.0
4   105   Sneha  22.0  Female     Nagpur   90.0
5   106   Rohit  21.0    Male       Pune   78.0

0    Sameer
1     Rahul
2     Priya
3      Amit
4     Sneha
5     Rohit
Name: Name, dtype: object

     Name  Marks
0  Sameer   89.0
1   Rahul   76.0
2   Priya   95.0
3    Amit   80.0
4   Sneha   90.0

    Roll     Name   Age  Gender       City  Marks
0    101   Sameer  22.0    Male  Hyderabad   89.0
2    103    Priya  20.0  Female     Mumbai   95.0
4    105    Sneha  22.0  Female     Nagpur   90.0
8    109    Pooja  22.0  Female     Mumbai   91.0
10   111     Neha  20.0  Female       Pune   88.0
13   114   Sachin  23.0    Male     Mumbai   86.0
14   115     Riya  20.0  Female       Pune   93.0
18   119    Meena  22.0  Female     Mumbai   87.0
21   122   Nikita  22.0  Female     Mumbai   92.0
25   126    Komal  20.0  Female  Hyderabad   89.0
27   128    Divya  22.0  Female       Pune   94.0
29   130   Shreya  20.0  Female     Nagpur   90.0
31   132    Payal  22.0  Female     Mumbai   88.0
33   134    Tanvi  20.0  Female      Delhi   91.0
36   137     Yash  23.0    Male     Mumbai   86.0
37   138  Pallavi  22.0  Female       Pune   93.0
39   140   Khushi  21.0  Female     Nagpur   90.0
42   143   Sameer  22.0    Male  Hyderabad   89.0
44   145    Sneha  22.0  Female        NaN   90.0
48   149    Pooja  22.0  Female     Mumbai   91.0

    Roll      Name   Age Gender    City  Marks
7    108     Karan  23.0   Male   Delhi   67.0
9    110     Vikas  21.0   Male  Nagpur   74.0
15   116     Mohan  22.0   Male  Nagpur   72.0
17   118    Deepak  23.0   Male   Delhi   69.0
24   125    Ramesh  22.0   Male  Nagpur   70.0
28   129     Nitin  23.0   Male   Delhi   71.0
34   135    Manish  22.0   Male  Nagpur   73.0
38   139  Abhishek  20.0   Male   Delhi   68.0
47   148     Karan  23.0   Male   Delhi   67.0
49   150     Vikas  21.0   Male  Nagpur   74.0

    Roll     Name   Age  Gender       City  Marks
0    101   Sameer  22.0    Male  Hyderabad   89.0
4    105    Sneha  22.0  Female     Nagpur   90.0
8    109    Pooja  22.0  Female     Mumbai   91.0
11   112    Arjun  22.0    Male  Hyderabad   82.0
15   116    Mohan  22.0    Male     Nagpur   72.0
18   119    Meena  22.0  Female     Mumbai   87.0
21   122   Nikita  22.0  Female     Mumbai   92.0
24   125   Ramesh  22.0    Male     Nagpur   70.0
27   128    Divya  22.0  Female       Pune   94.0
31   132    Payal  22.0  Female     Mumbai   88.0
34   135   Manish  22.0    Male     Nagpur   73.0
37   138  Pallavi  22.0  Female       Pune   93.0
41   142      NaN  22.0  Female     Mumbai   85.0
42   143   Sameer  22.0    Male  Hyderabad   89.0
44   145    Sneha  22.0  Female        NaN   90.0
48   149    Pooja  22.0  Female     Mumbai   91.0

    Roll    Name   Age  Gender       City  Marks
0    101  Sameer  22.0    Male  Hyderabad   89.0
6    107  Anjali  20.0  Female  Hyderabad   85.0
11   112   Arjun  22.0    Male  Hyderabad   82.0
16   117  Simran  21.0  Female  Hyderabad   84.0
20   121    Ajay  20.0    Male  Hyderabad   81.0
25   126   Komal  20.0  Female  Hyderabad   89.0
30   131   Vinay  21.0    Male  Hyderabad   76.0
35   136   Swati  21.0  Female  Hyderabad   84.0
42   143  Sameer  22.0    Male  Hyderabad   89.0
46   147  Anjali  20.0  Female  Hyderabad   85.0

    Roll      Name   Age  Gender       City  Marks
0    101    Sameer  22.0    Male  Hyderabad   89.0
2    103     Priya  20.0  Female     Mumbai   95.0
3    104      Amit  23.0    Male      Delhi   80.0
4    105     Sneha  22.0  Female     Nagpur   90.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
7    108     Karan  23.0    Male      Delhi   67.0
8    109     Pooja  22.0  Female     Mumbai   91.0
9    110     Vikas  21.0    Male     Nagpur   74.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
12   113    Kavita  21.0  Female      Delhi   79.0
13   114    Sachin  23.0    Male     Mumbai   86.0
15   116     Mohan  22.0    Male     Nagpur   72.0
16   117    Simran  21.0  Female  Hyderabad   84.0
17   118    Deepak  23.0    Male      Delhi   69.0
18   119     Meena  22.0  Female     Mumbai   87.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
21   122    Nikita  22.0  Female     Mumbai   92.0
23   124     Aarti  23.0  Female      Delhi   83.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
25   126     Komal  20.0  Female  Hyderabad   89.0
26   127     Harsh  21.0    Male     Mumbai   85.0
28   129     Nitin  23.0    Male      Delhi   71.0
29   130    Shreya  20.0  Female     Nagpur   90.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
31   132     Payal  22.0  Female     Mumbai   88.0
33   134     Tanvi  20.0  Female      Delhi   91.0
34   135    Manish  22.0    Male     Nagpur   73.0
35   136     Swati  21.0  Female  Hyderabad   84.0
36   137      Yash  23.0    Male     Mumbai   86.0
38   139  Abhishek  20.0    Male      Delhi   68.0
39   140    Khushi  21.0  Female     Nagpur   90.0
41   142       NaN  22.0  Female     Mumbai   85.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
43   144      Amit   NaN    Male      Delhi   80.0
44   145     Sneha  22.0  Female        NaN   90.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
47   148     Karan  23.0    Male      Delhi   67.0
48   149     Pooja  22.0  Female     Mumbai   91.0
49   150     Vikas  21.0    Male     Nagpur   74.0

    Roll     Name   Age  Gender    City  Marks
2    103    Priya  20.0  Female  Mumbai   95.0
4    105    Sneha  22.0  Female  Nagpur   90.0
8    109    Pooja  22.0  Female  Mumbai   91.0
14   115     Riya  20.0  Female    Pune   93.0
21   122   Nikita  22.0  Female  Mumbai   92.0
27   128    Divya  22.0  Female    Pune   94.0
29   130   Shreya  20.0  Female  Nagpur   90.0
33   134    Tanvi  20.0  Female   Delhi   91.0
37   138  Pallavi  22.0  Female    Pune   93.0
39   140   Khushi  21.0  Female  Nagpur   90.0
44   145    Sneha  22.0  Female     NaN   90.0
48   149    Pooja  22.0  Female  Mumbai   91.0

    Roll    Name   Age  Gender       City  Marks
0    101  Sameer  22.0    Male  Hyderabad   89.0
3    104    Amit  23.0    Male      Delhi   80.0
4    105   Sneha  22.0  Female     Nagpur   90.0
6    107  Anjali  20.0  Female  Hyderabad   85.0
10   111    Neha  20.0  Female       Pune   88.0
11   112   Arjun  22.0    Male  Hyderabad   82.0
13   114  Sachin  23.0    Male     Mumbai   86.0
16   117  Simran  21.0  Female  Hyderabad   84.0
18   119   Meena  22.0  Female     Mumbai   87.0
20   121    Ajay  20.0    Male  Hyderabad   81.0
23   124   Aarti  23.0  Female      Delhi   83.0
25   126   Komal  20.0  Female  Hyderabad   89.0
26   127   Harsh  21.0    Male     Mumbai   85.0
29   130  Shreya  20.0  Female     Nagpur   90.0
31   132   Payal  22.0  Female     Mumbai   88.0
35   136   Swati  21.0  Female  Hyderabad   84.0
36   137    Yash  23.0    Male     Mumbai   86.0
39   140  Khushi  21.0  Female     Nagpur   90.0
41   142     NaN  22.0  Female     Mumbai   85.0
42   143  Sameer  22.0    Male  Hyderabad   89.0
43   144    Amit   NaN    Male      Delhi   80.0
44   145   Sneha  22.0  Female        NaN   90.0
46   147  Anjali  20.0  Female  Hyderabad   85.0

    Roll      Name   Age  Gender       City  Marks
1    102     Rahul  21.0    Male       Pune   76.0
2    103     Priya  20.0  Female     Mumbai   95.0
5    106     Rohit  21.0    Male       Pune   78.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
9    110     Vikas  21.0    Male     Nagpur   74.0
10   111      Neha  20.0  Female       Pune   88.0
12   113    Kavita  21.0  Female      Delhi   79.0
14   115      Riya  20.0  Female       Pune   93.0
16   117    Simran  21.0  Female  Hyderabad   84.0
19   120     Akash  21.0    Male       Pune   75.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
22   123     Sumit  21.0    Male       Pune   77.0
25   126     Komal  20.0  Female  Hyderabad   89.0
26   127     Harsh  21.0    Male     Mumbai   85.0
29   130    Shreya  20.0  Female     Nagpur   90.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
33   134     Tanvi  20.0  Female      Delhi   91.0
35   136     Swati  21.0  Female  Hyderabad   84.0
38   139  Abhishek  20.0    Male      Delhi   68.0
39   140    Khushi  21.0  Female     Nagpur   90.0
40   141     Rahul  21.0    Male       Pune   76.0
45   146     Rohit  21.0    Male       Pune    NaN
46   147    Anjali  20.0  Female  Hyderabad   85.0
49   150     Vikas  21.0    Male     Nagpur   74.0

    Roll     Name   Age  Gender    City  Marks
1    102    Rahul  21.0    Male    Pune   76.0
2    103    Priya  20.0  Female  Mumbai   95.0
5    106    Rohit  21.0    Male    Pune   78.0
8    109    Pooja  22.0  Female  Mumbai   91.0
10   111     Neha  20.0  Female    Pune   88.0
13   114   Sachin  23.0    Male  Mumbai   86.0
14   115     Riya  20.0  Female    Pune   93.0
18   119    Meena  22.0  Female  Mumbai   87.0
19   120    Akash  21.0    Male    Pune   75.0
21   122   Nikita  22.0  Female  Mumbai   92.0
22   123    Sumit  21.0    Male    Pune   77.0
26   127    Harsh  21.0    Male  Mumbai   85.0
27   128    Divya  22.0  Female    Pune   94.0
31   132    Payal  22.0  Female  Mumbai   88.0
32   133    Sagar  23.0    Male    Pune   79.0
36   137     Yash  23.0    Male  Mumbai   86.0
37   138  Pallavi  22.0  Female    Pune   93.0
40   141    Rahul  21.0    Male    Pune   76.0
41   142      NaN  22.0  Female  Mumbai   85.0
45   146    Rohit  21.0    Male    Pune    NaN
48   149    Pooja  22.0  Female  Mumbai   91.0

    Roll    Name   Age  Gender       City  Marks
0    101  Sameer  22.0    Male  Hyderabad   89.0
6    107  Anjali  20.0  Female  Hyderabad   85.0
11   112   Arjun  22.0    Male  Hyderabad   82.0
16   117  Simran  21.0  Female  Hyderabad   84.0
20   121    Ajay  20.0    Male  Hyderabad   81.0
25   126   Komal  20.0  Female  Hyderabad   89.0
35   136   Swati  21.0  Female  Hyderabad   84.0
42   143  Sameer  22.0    Male  Hyderabad   89.0
46   147  Anjali  20.0  Female  Hyderabad   85.0

    Roll      Name   Age  Gender    City  Marks
1    102     Rahul  21.0    Male    Pune   76.0
2    103     Priya  20.0  Female  Mumbai   95.0
3    104      Amit  23.0    Male   Delhi   80.0
5    106     Rohit  21.0    Male    Pune   78.0
7    108     Karan  23.0    Male   Delhi   67.0
8    109     Pooja  22.0  Female  Mumbai   91.0
10   111      Neha  20.0  Female    Pune   88.0
12   113    Kavita  21.0  Female   Delhi   79.0
13   114    Sachin  23.0    Male  Mumbai   86.0
14   115      Riya  20.0  Female    Pune   93.0
17   118    Deepak  23.0    Male   Delhi   69.0
18   119     Meena  22.0  Female  Mumbai   87.0
19   120     Akash  21.0    Male    Pune   75.0
21   122    Nikita  22.0  Female  Mumbai   92.0
22   123     Sumit  21.0    Male    Pune   77.0
23   124     Aarti  23.0  Female   Delhi   83.0
26   127     Harsh  21.0    Male  Mumbai   85.0
27   128     Divya  22.0  Female    Pune   94.0
28   129     Nitin  23.0    Male   Delhi   71.0
31   132     Payal  22.0  Female  Mumbai   88.0
32   133     Sagar  23.0    Male    Pune   79.0
33   134     Tanvi  20.0  Female   Delhi   91.0
36   137      Yash  23.0    Male  Mumbai   86.0
37   138   Pallavi  22.0  Female    Pune   93.0
38   139  Abhishek  20.0    Male   Delhi   68.0
40   141     Rahul  21.0    Male    Pune   76.0
41   142       NaN  22.0  Female  Mumbai   85.0
43   144      Amit   NaN    Male   Delhi   80.0
45   146     Rohit  21.0    Male    Pune    NaN
47   148     Karan  23.0    Male   Delhi   67.0
48   149     Pooja  22.0  Female  Mumbai   91.0

0      Sameer
2       Priya
4       Sneha
8       Pooja
10       Neha
13     Sachin
14       Riya
18      Meena
21     Nikita
25      Komal
27      Divya
29     Shreya
31      Payal
33      Tanvi
36       Yash
37    Pallavi
39     Khushi
42     Sameer
44      Sneha
48      Pooja
Name: Name, dtype: object

2       Priya
4       Sneha
8       Pooja
10       Neha
14       Riya
18      Meena
21     Nikita
25      Komal
27      Divya
29     Shreya
31      Payal
33      Tanvi
37    Pallavi
39     Khushi
44      Sneha
48      Pooja
Name: Name, dtype: object

    Roll    Name   Age  Gender       City  Marks
10   111    Neha  20.0  Female       Pune   88.0
11   112   Arjun  22.0    Male  Hyderabad   82.0
12   113  Kavita  21.0  Female      Delhi   79.0
13   114  Sachin  23.0    Male     Mumbai   86.0
14   115    Riya  20.0  Female       Pune   93.0
15   116   Mohan  22.0    Male     Nagpur   72.0
16   117  Simran  21.0  Female  Hyderabad   84.0
17   118  Deepak  23.0    Male      Delhi   69.0
18   119   Meena  22.0  Female     Mumbai   87.0
19   120   Akash  21.0    Male       Pune   75.0
20   121    Ajay  20.0    Male  Hyderabad   81.0

    Roll    Name   Age  Gender       City  Marks
10   111    Neha  20.0  Female       Pune   88.0
11   112   Arjun  22.0    Male  Hyderabad   82.0
12   113  Kavita  21.0  Female      Delhi   79.0
13   114  Sachin  23.0    Male     Mumbai   86.0
14   115    Riya  20.0  Female       Pune   93.0
15   116   Mohan  22.0    Male     Nagpur   72.0
16   117  Simran  21.0  Female  Hyderabad   84.0
17   118  Deepak  23.0    Male      Delhi   69.0
18   119   Meena  22.0  Female     Mumbai   87.0
19   120   Akash  21.0    Male       Pune   75.0
20   121    Ajay  20.0    Male  Hyderabad   81.0

In [47]:
df

    Roll      Name   Age  Gender       City  Marks
0    101    Sameer  22.0    Male  Hyderabad   89.0
1    102     Rahul  21.0    Male       Pune   76.0
2    103     Priya  20.0  Female     Mumbai   95.0
3    104      Amit  23.0    Male      Delhi   80.0
4    105     Sneha  22.0  Female     Nagpur   90.0
5    106     Rohit  21.0    Male       Pune   78.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
7    108     Karan  23.0    Male      Delhi   67.0
8    109     Pooja  22.0  Female     Mumbai   91.0
9    110     Vikas  21.0    Male     Nagpur   74.0
10   111      Neha  20.0  Female       Pune   88.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
12   113    Kavita  21.0  Female      Delhi   79.0
13   114    Sachin  23.0    Male     Mumbai   86.0
14   115      Riya  20.0  Female       Pune   93.0
15   116     Mohan  22.0    Male     Nagpur   72.0
16   117    Simran  21.0  Female  Hyderabad   84.0
17   118    Deepak  23.0    Male      Delhi   69.0
18   119     Meena  22.0  Female     Mumbai   87.0
19   120     Akash  21.0    Male       Pune   75.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
21   122    Nikita  22.0  Female     Mumbai   92.0
22   123     Sumit  21.0    Male       Pune   77.0
23   124     Aarti  23.0  Female      Delhi   83.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
25   126     Komal  20.0  Female  Hyderabad   89.0
26   127     Harsh  21.0    Male     Mumbai   85.0
27   128     Divya  22.0  Female       Pune   94.0
28   129     Nitin  23.0    Male      Delhi   71.0
29   130    Shreya  20.0  Female     Nagpur   90.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
31   132     Payal  22.0  Female     Mumbai   88.0
32   133     Sagar  23.0    Male       Pune   79.0
33   134     Tanvi  20.0  Female      Delhi   91.0
34   135    Manish  22.0    Male     Nagpur   73.0
35   136     Swati  21.0  Female  Hyderabad   84.0
36   137      Yash  23.0    Male     Mumbai   86.0
37   138   Pallavi  22.0  Female       Pune   93.0
38   139  Abhishek  20.0    Male      Delhi   68.0
39   140    Khushi  21.0  Female     Nagpur   90.0
40   141     Rahul  21.0    Male       Pune   76.0
41   142       NaN  22.0  Female     Mumbai   85.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
43   144      Amit   NaN    Male      Delhi   80.0
44   145     Sneha  22.0  Female        NaN   90.0
45   146     Rohit  21.0    Male       Pune    NaN
46   147    Anjali  20.0  Female  Hyderabad   85.0
47   148     Karan  23.0    Male      Delhi   67.0
48   149     Pooja  22.0  Female     Mumbai   91.0
49   150     Vikas  21.0    Male     Nagpur   74.0

In [64]:
# Module 5
# Basic
# Sort students by Marks in ascending order.
print(df.sort_values(by="Marks"))
# Sort students by Marks in descending order.
print()
print(df.sort_values(by="Marks",ascending=False))
# Sort students by Age.
print()
print(df.sort_values(by="Age"))
# Sort students by Name alphabetically.
print()
print(df.sort_values(by="Name"))
# Sort students by City.
print()
print(df.sort_values(by="City"))
# Intermediate
# Sort students by City and then by Marks.
print()
print(df.sort_values(by=["City","Marks"]))
# Sort students by City (A–Z) and Marks (highest first).
print()
print(df.sort_values(by=["City","Marks"],ascending=[True,False]))
# Sort the DataFrame by index in ascending order.
print()
print(df.sort_index())
# Sort the DataFrame by index in descending order.
print()
print(df.sort_index(ascending=False))
# Advanced
# Show the top 5 students with the highest marks.
print()
print(df.nlargest(5,"Marks"))
# Show the top 3 oldest students.
print()
print(df.nlargest(3,"Age"))
# Show the 5 students with the lowest marks.
print()
print(df.nsmallest(5,"Marks"))
# Show the 10 youngest students.
print()
print(df.nsmallest(10,"Age"))
# Find the top 5 students from the sorted DataFrame by marks.
print()
sorted_df = df.sort_values(by="Marks", ascending=False)

print(sorted_df.head(5))

# Compare the output of sort_values(by="Marks") and nlargest(5, "Marks").
print()
print(df.sort_values(by="Marks", ascending=False))
print()
print(df.nlargest(5,"Marks"))

    Roll      Name   Age  Gender       City  Marks
47   148     Karan  23.0    Male      Delhi   67.0
7    108     Karan  23.0    Male      Delhi   67.0
38   139  Abhishek  20.0    Male      Delhi   68.0
17   118    Deepak  23.0    Male      Delhi   69.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
28   129     Nitin  23.0    Male      Delhi   71.0
15   116     Mohan  22.0    Male     Nagpur   72.0
34   135    Manish  22.0    Male     Nagpur   73.0
9    110     Vikas  21.0    Male     Nagpur   74.0
49   150     Vikas  21.0    Male     Nagpur   74.0
19   120     Akash  21.0    Male       Pune   75.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
1    102     Rahul  21.0    Male       Pune   76.0
40   141     Rahul  21.0    Male       Pune   76.0
22   123     Sumit  21.0    Male       Pune   77.0
5    106     Rohit  21.0    Male       Pune   78.0
32   133     Sagar  23.0    Male       Pune   79.0
12   113    Kavita  21.0  Female      Delhi   79.0
43   144      Amit   NaN    Male      Delhi   80.0
3    104      Amit  23.0    Male      Delhi   80.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
23   124     Aarti  23.0  Female      Delhi   83.0
35   136     Swati  21.0  Female  Hyderabad   84.0
16   117    Simran  21.0  Female  Hyderabad   84.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
26   127     Harsh  21.0    Male     Mumbai   85.0
41   142       NaN  22.0  Female     Mumbai   85.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
36   137      Yash  23.0    Male     Mumbai   86.0
13   114    Sachin  23.0    Male     Mumbai   86.0
18   119     Meena  22.0  Female     Mumbai   87.0
31   132     Payal  22.0  Female     Mumbai   88.0
10   111      Neha  20.0  Female       Pune   88.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
0    101    Sameer  22.0    Male  Hyderabad   89.0
25   126     Komal  20.0  Female  Hyderabad   89.0
39   140    Khushi  21.0  Female     Nagpur   90.0
4    105     Sneha  22.0  Female     Nagpur   90.0
44   145     Sneha  22.0  Female        NaN   90.0
29   130    Shreya  20.0  Female     Nagpur   90.0
8    109     Pooja  22.0  Female     Mumbai   91.0
48   149     Pooja  22.0  Female     Mumbai   91.0
33   134     Tanvi  20.0  Female      Delhi   91.0
21   122    Nikita  22.0  Female     Mumbai   92.0
37   138   Pallavi  22.0  Female       Pune   93.0
14   115      Riya  20.0  Female       Pune   93.0
27   128     Divya  22.0  Female       Pune   94.0
2    103     Priya  20.0  Female     Mumbai   95.0
45   146     Rohit  21.0    Male       Pune    NaN

    Roll      Name   Age  Gender       City  Marks
2    103     Priya  20.0  Female     Mumbai   95.0
27   128     Divya  22.0  Female       Pune   94.0
37   138   Pallavi  22.0  Female       Pune   93.0
14   115      Riya  20.0  Female       Pune   93.0
21   122    Nikita  22.0  Female     Mumbai   92.0
33   134     Tanvi  20.0  Female      Delhi   91.0
48   149     Pooja  22.0  Female     Mumbai   91.0
8    109     Pooja  22.0  Female     Mumbai   91.0
4    105     Sneha  22.0  Female     Nagpur   90.0
39   140    Khushi  21.0  Female     Nagpur   90.0
29   130    Shreya  20.0  Female     Nagpur   90.0
44   145     Sneha  22.0  Female        NaN   90.0
25   126     Komal  20.0  Female  Hyderabad   89.0
0    101    Sameer  22.0    Male  Hyderabad   89.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
31   132     Payal  22.0  Female     Mumbai   88.0
10   111      Neha  20.0  Female       Pune   88.0
18   119     Meena  22.0  Female     Mumbai   87.0
13   114    Sachin  23.0    Male     Mumbai   86.0
36   137      Yash  23.0    Male     Mumbai   86.0
26   127     Harsh  21.0    Male     Mumbai   85.0
41   142       NaN  22.0  Female     Mumbai   85.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
35   136     Swati  21.0  Female  Hyderabad   84.0
16   117    Simran  21.0  Female  Hyderabad   84.0
23   124     Aarti  23.0  Female      Delhi   83.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
3    104      Amit  23.0    Male      Delhi   80.0
43   144      Amit   NaN    Male      Delhi   80.0
12   113    Kavita  21.0  Female      Delhi   79.0
32   133     Sagar  23.0    Male       Pune   79.0
5    106     Rohit  21.0    Male       Pune   78.0
22   123     Sumit  21.0    Male       Pune   77.0
40   141     Rahul  21.0    Male       Pune   76.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
1    102     Rahul  21.0    Male       Pune   76.0
19   120     Akash  21.0    Male       Pune   75.0
49   150     Vikas  21.0    Male     Nagpur   74.0
9    110     Vikas  21.0    Male     Nagpur   74.0
34   135    Manish  22.0    Male     Nagpur   73.0
15   116     Mohan  22.0    Male     Nagpur   72.0
28   129     Nitin  23.0    Male      Delhi   71.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
17   118    Deepak  23.0    Male      Delhi   69.0
38   139  Abhishek  20.0    Male      Delhi   68.0
47   148     Karan  23.0    Male      Delhi   67.0
7    108     Karan  23.0    Male      Delhi   67.0
45   146     Rohit  21.0    Male       Pune    NaN

    Roll      Name   Age  Gender       City  Marks
14   115      Riya  20.0  Female       Pune   93.0
25   126     Komal  20.0  Female  Hyderabad   89.0
33   134     Tanvi  20.0  Female      Delhi   91.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
38   139  Abhishek  20.0    Male      Delhi   68.0
10   111      Neha  20.0  Female       Pune   88.0
29   130    Shreya  20.0  Female     Nagpur   90.0
2    103     Priya  20.0  Female     Mumbai   95.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
22   123     Sumit  21.0    Male       Pune   77.0
35   136     Swati  21.0  Female  Hyderabad   84.0
19   120     Akash  21.0    Male       Pune   75.0
45   146     Rohit  21.0    Male       Pune    NaN
16   117    Simran  21.0  Female  Hyderabad   84.0
49   150     Vikas  21.0    Male     Nagpur   74.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
40   141     Rahul  21.0    Male       Pune   76.0
12   113    Kavita  21.0  Female      Delhi   79.0
26   127     Harsh  21.0    Male     Mumbai   85.0
5    106     Rohit  21.0    Male       Pune   78.0
9    110     Vikas  21.0    Male     Nagpur   74.0
1    102     Rahul  21.0    Male       Pune   76.0
39   140    Khushi  21.0  Female     Nagpur   90.0
31   132     Payal  22.0  Female     Mumbai   88.0
44   145     Sneha  22.0  Female        NaN   90.0
41   142       NaN  22.0  Female     Mumbai   85.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
34   135    Manish  22.0    Male     Nagpur   73.0
37   138   Pallavi  22.0  Female       Pune   93.0
0    101    Sameer  22.0    Male  Hyderabad   89.0
27   128     Divya  22.0  Female       Pune   94.0
4    105     Sneha  22.0  Female     Nagpur   90.0
8    109     Pooja  22.0  Female     Mumbai   91.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
18   119     Meena  22.0  Female     Mumbai   87.0
15   116     Mohan  22.0    Male     Nagpur   72.0
21   122    Nikita  22.0  Female     Mumbai   92.0
48   149     Pooja  22.0  Female     Mumbai   91.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
17   118    Deepak  23.0    Male      Delhi   69.0
28   129     Nitin  23.0    Male      Delhi   71.0
13   114    Sachin  23.0    Male     Mumbai   86.0
23   124     Aarti  23.0  Female      Delhi   83.0
7    108     Karan  23.0    Male      Delhi   67.0
32   133     Sagar  23.0    Male       Pune   79.0
3    104      Amit  23.0    Male      Delhi   80.0
47   148     Karan  23.0    Male      Delhi   67.0
36   137      Yash  23.0    Male     Mumbai   86.0
43   144      Amit   NaN    Male      Delhi   80.0

    Roll      Name   Age  Gender       City  Marks
23   124     Aarti  23.0  Female      Delhi   83.0
38   139  Abhishek  20.0    Male      Delhi   68.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
19   120     Akash  21.0    Male       Pune   75.0
43   144      Amit   NaN    Male      Delhi   80.0
3    104      Amit  23.0    Male      Delhi   80.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
17   118    Deepak  23.0    Male      Delhi   69.0
27   128     Divya  22.0  Female       Pune   94.0
26   127     Harsh  21.0    Male     Mumbai   85.0
7    108     Karan  23.0    Male      Delhi   67.0
47   148     Karan  23.0    Male      Delhi   67.0
12   113    Kavita  21.0  Female      Delhi   79.0
39   140    Khushi  21.0  Female     Nagpur   90.0
25   126     Komal  20.0  Female  Hyderabad   89.0
34   135    Manish  22.0    Male     Nagpur   73.0
18   119     Meena  22.0  Female     Mumbai   87.0
15   116     Mohan  22.0    Male     Nagpur   72.0
10   111      Neha  20.0  Female       Pune   88.0
21   122    Nikita  22.0  Female     Mumbai   92.0
28   129     Nitin  23.0    Male      Delhi   71.0
37   138   Pallavi  22.0  Female       Pune   93.0
31   132     Payal  22.0  Female     Mumbai   88.0
48   149     Pooja  22.0  Female     Mumbai   91.0
8    109     Pooja  22.0  Female     Mumbai   91.0
2    103     Priya  20.0  Female     Mumbai   95.0
40   141     Rahul  21.0    Male       Pune   76.0
1    102     Rahul  21.0    Male       Pune   76.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
14   115      Riya  20.0  Female       Pune   93.0
5    106     Rohit  21.0    Male       Pune   78.0
45   146     Rohit  21.0    Male       Pune    NaN
13   114    Sachin  23.0    Male     Mumbai   86.0
32   133     Sagar  23.0    Male       Pune   79.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
0    101    Sameer  22.0    Male  Hyderabad   89.0
29   130    Shreya  20.0  Female     Nagpur   90.0
16   117    Simran  21.0  Female  Hyderabad   84.0
44   145     Sneha  22.0  Female        NaN   90.0
4    105     Sneha  22.0  Female     Nagpur   90.0
22   123     Sumit  21.0    Male       Pune   77.0
35   136     Swati  21.0  Female  Hyderabad   84.0
33   134     Tanvi  20.0  Female      Delhi   91.0
9    110     Vikas  21.0    Male     Nagpur   74.0
49   150     Vikas  21.0    Male     Nagpur   74.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
36   137      Yash  23.0    Male     Mumbai   86.0
41   142       NaN  22.0  Female     Mumbai   85.0

    Roll      Name   Age  Gender       City  Marks
38   139  Abhishek  20.0    Male      Delhi   68.0
47   148     Karan  23.0    Male      Delhi   67.0
33   134     Tanvi  20.0  Female      Delhi   91.0
3    104      Amit  23.0    Male      Delhi   80.0
28   129     Nitin  23.0    Male      Delhi   71.0
43   144      Amit   NaN    Male      Delhi   80.0
7    108     Karan  23.0    Male      Delhi   67.0
23   124     Aarti  23.0  Female      Delhi   83.0
17   118    Deepak  23.0    Male      Delhi   69.0
12   113    Kavita  21.0  Female      Delhi   79.0
25   126     Komal  20.0  Female  Hyderabad   89.0
35   136     Swati  21.0  Female  Hyderabad   84.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
16   117    Simran  21.0  Female  Hyderabad   84.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
0    101    Sameer  22.0    Male  Hyderabad   89.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
13   114    Sachin  23.0    Male     Mumbai   86.0
18   119     Meena  22.0  Female     Mumbai   87.0
36   137      Yash  23.0    Male     Mumbai   86.0
41   142       NaN  22.0  Female     Mumbai   85.0
21   122    Nikita  22.0  Female     Mumbai   92.0
8    109     Pooja  22.0  Female     Mumbai   91.0
48   149     Pooja  22.0  Female     Mumbai   91.0
26   127     Harsh  21.0    Male     Mumbai   85.0
2    103     Priya  20.0  Female     Mumbai   95.0
31   132     Payal  22.0  Female     Mumbai   88.0
34   135    Manish  22.0    Male     Nagpur   73.0
39   140    Khushi  21.0  Female     Nagpur   90.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
29   130    Shreya  20.0  Female     Nagpur   90.0
15   116     Mohan  22.0    Male     Nagpur   72.0
9    110     Vikas  21.0    Male     Nagpur   74.0
4    105     Sneha  22.0  Female     Nagpur   90.0
49   150     Vikas  21.0    Male     Nagpur   74.0
27   128     Divya  22.0  Female       Pune   94.0
22   123     Sumit  21.0    Male       Pune   77.0
19   120     Akash  21.0    Male       Pune   75.0
37   138   Pallavi  22.0  Female       Pune   93.0
14   115      Riya  20.0  Female       Pune   93.0
40   141     Rahul  21.0    Male       Pune   76.0
10   111      Neha  20.0  Female       Pune   88.0
5    106     Rohit  21.0    Male       Pune   78.0
45   146     Rohit  21.0    Male       Pune    NaN
1    102     Rahul  21.0    Male       Pune   76.0
32   133     Sagar  23.0    Male       Pune   79.0
44   145     Sneha  22.0  Female        NaN   90.0

    Roll      Name   Age  Gender       City  Marks
7    108     Karan  23.0    Male      Delhi   67.0
47   148     Karan  23.0    Male      Delhi   67.0
38   139  Abhishek  20.0    Male      Delhi   68.0
17   118    Deepak  23.0    Male      Delhi   69.0
28   129     Nitin  23.0    Male      Delhi   71.0
12   113    Kavita  21.0  Female      Delhi   79.0
3    104      Amit  23.0    Male      Delhi   80.0
43   144      Amit   NaN    Male      Delhi   80.0
23   124     Aarti  23.0  Female      Delhi   83.0
33   134     Tanvi  20.0  Female      Delhi   91.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
16   117    Simran  21.0  Female  Hyderabad   84.0
35   136     Swati  21.0  Female  Hyderabad   84.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
0    101    Sameer  22.0    Male  Hyderabad   89.0
25   126     Komal  20.0  Female  Hyderabad   89.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
26   127     Harsh  21.0    Male     Mumbai   85.0
41   142       NaN  22.0  Female     Mumbai   85.0
13   114    Sachin  23.0    Male     Mumbai   86.0
36   137      Yash  23.0    Male     Mumbai   86.0
18   119     Meena  22.0  Female     Mumbai   87.0
31   132     Payal  22.0  Female     Mumbai   88.0
8    109     Pooja  22.0  Female     Mumbai   91.0
48   149     Pooja  22.0  Female     Mumbai   91.0
21   122    Nikita  22.0  Female     Mumbai   92.0
2    103     Priya  20.0  Female     Mumbai   95.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
15   116     Mohan  22.0    Male     Nagpur   72.0
34   135    Manish  22.0    Male     Nagpur   73.0
9    110     Vikas  21.0    Male     Nagpur   74.0
49   150     Vikas  21.0    Male     Nagpur   74.0
4    105     Sneha  22.0  Female     Nagpur   90.0
29   130    Shreya  20.0  Female     Nagpur   90.0
39   140    Khushi  21.0  Female     Nagpur   90.0
19   120     Akash  21.0    Male       Pune   75.0
1    102     Rahul  21.0    Male       Pune   76.0
40   141     Rahul  21.0    Male       Pune   76.0
22   123     Sumit  21.0    Male       Pune   77.0
5    106     Rohit  21.0    Male       Pune   78.0
32   133     Sagar  23.0    Male       Pune   79.0
10   111      Neha  20.0  Female       Pune   88.0
14   115      Riya  20.0  Female       Pune   93.0
37   138   Pallavi  22.0  Female       Pune   93.0
27   128     Divya  22.0  Female       Pune   94.0
45   146     Rohit  21.0    Male       Pune    NaN
44   145     Sneha  22.0  Female        NaN   90.0

    Roll      Name   Age  Gender       City  Marks
33   134     Tanvi  20.0  Female      Delhi   91.0
23   124     Aarti  23.0  Female      Delhi   83.0
3    104      Amit  23.0    Male      Delhi   80.0
43   144      Amit   NaN    Male      Delhi   80.0
12   113    Kavita  21.0  Female      Delhi   79.0
28   129     Nitin  23.0    Male      Delhi   71.0
17   118    Deepak  23.0    Male      Delhi   69.0
38   139  Abhishek  20.0    Male      Delhi   68.0
7    108     Karan  23.0    Male      Delhi   67.0
47   148     Karan  23.0    Male      Delhi   67.0
0    101    Sameer  22.0    Male  Hyderabad   89.0
25   126     Komal  20.0  Female  Hyderabad   89.0
42   143    Sameer  22.0    Male  Hyderabad   89.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
46   147    Anjali  20.0  Female  Hyderabad   85.0
16   117    Simran  21.0  Female  Hyderabad   84.0
35   136     Swati  21.0  Female  Hyderabad   84.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
2    103     Priya  20.0  Female     Mumbai   95.0
21   122    Nikita  22.0  Female     Mumbai   92.0
8    109     Pooja  22.0  Female     Mumbai   91.0
48   149     Pooja  22.0  Female     Mumbai   91.0
31   132     Payal  22.0  Female     Mumbai   88.0
18   119     Meena  22.0  Female     Mumbai   87.0
13   114    Sachin  23.0    Male     Mumbai   86.0
36   137      Yash  23.0    Male     Mumbai   86.0
26   127     Harsh  21.0    Male     Mumbai   85.0
41   142       NaN  22.0  Female     Mumbai   85.0
4    105     Sneha  22.0  Female     Nagpur   90.0
29   130    Shreya  20.0  Female     Nagpur   90.0
39   140    Khushi  21.0  Female     Nagpur   90.0
9    110     Vikas  21.0    Male     Nagpur   74.0
49   150     Vikas  21.0    Male     Nagpur   74.0
34   135    Manish  22.0    Male     Nagpur   73.0
15   116     Mohan  22.0    Male     Nagpur   72.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
27   128     Divya  22.0  Female       Pune   94.0
14   115      Riya  20.0  Female       Pune   93.0
37   138   Pallavi  22.0  Female       Pune   93.0
10   111      Neha  20.0  Female       Pune   88.0
32   133     Sagar  23.0    Male       Pune   79.0
5    106     Rohit  21.0    Male       Pune   78.0
22   123     Sumit  21.0    Male       Pune   77.0
1    102     Rahul  21.0    Male       Pune   76.0
40   141     Rahul  21.0    Male       Pune   76.0
19   120     Akash  21.0    Male       Pune   75.0
45   146     Rohit  21.0    Male       Pune    NaN
44   145     Sneha  22.0  Female        NaN   90.0

    Roll      Name   Age  Gender       City  Marks
0    101    Sameer  22.0    Male  Hyderabad   89.0
1    102     Rahul  21.0    Male       Pune   76.0
2    103     Priya  20.0  Female     Mumbai   95.0
3    104      Amit  23.0    Male      Delhi   80.0
4    105     Sneha  22.0  Female     Nagpur   90.0
5    106     Rohit  21.0    Male       Pune   78.0
6    107    Anjali  20.0  Female  Hyderabad   85.0
7    108     Karan  23.0    Male      Delhi   67.0
8    109     Pooja  22.0  Female     Mumbai   91.0
9    110     Vikas  21.0    Male     Nagpur   74.0
10   111      Neha  20.0  Female       Pune   88.0
11   112     Arjun  22.0    Male  Hyderabad   82.0
12   113    Kavita  21.0  Female      Delhi   79.0
13   114    Sachin  23.0    Male     Mumbai   86.0
14   115      Riya  20.0  Female       Pune   93.0
15   116     Mohan  22.0    Male     Nagpur   72.0
16   117    Simran  21.0  Female  Hyderabad   84.0
17   118    Deepak  23.0    Male      Delhi   69.0
18   119     Meena  22.0  Female     Mumbai   87.0
19   120     Akash  21.0    Male       Pune   75.0
20   121      Ajay  20.0    Male  Hyderabad   81.0
21   122    Nikita  22.0  Female     Mumbai   92.0
22   123     Sumit  21.0    Male       Pune   77.0
23   124     Aarti  23.0  Female      Delhi   83.0
24   125    Ramesh  22.0    Male     Nagpur   70.0
25   126     Komal  20.0  Female  Hyderabad   89.0
26   127     Harsh  21.0    Male     Mumbai   85.0
27   128     Divya  22.0  Female       Pune   94.0
28   129     Nitin  23.0    Male      Delhi   71.0
29   130    Shreya  20.0  Female     Nagpur   90.0
30   131     Vinay  21.0    Male  Hyderabad   76.0
31   132     Payal  22.0  Female     Mumbai   88.0
32   133     Sagar  23.0    Male       Pune   79.0
33   134     Tanvi  20.0  Female      Delhi   91.0

In [77]:
df

    Roll      Name   Age Grade  Gender       City  Marks Country
0    101    Sameer  22.0     A    Male  Hyderabad   89.0   India
1    102     Rahul  21.0     B    Male       Pune   76.0   India
2    103     Priya  20.0     C  Female     Mumbai   95.0   India
3    104      Amit  23.0     A    Male      Delhi   80.0   India
4    105     Sneha  22.0     B  Female     Nagpur   90.0   India
5    106     Rohit  21.0     C    Male       Pune   78.0   India
6    107    Anjali  20.0     A  Female  Hyderabad   85.0   India
7    108     Karan  23.0     B    Male      Delhi   67.0   India
8    109     Pooja  22.0     C  Female     Mumbai   91.0   India
9    110     Vikas  21.0     A    Male     Nagpur   74.0   India
10   111      Neha  20.0     B  Female       Pune   88.0   India
11   112     Arjun  22.0     C    Male  Hyderabad   82.0   India
12   113    Kavita  21.0     A  Female      Delhi   79.0   India
13   114    Sachin  23.0     B    Male     Mumbai   86.0   India
14   115      Riya  20.0     C  Female       Pune   93.0   India
15   116     Mohan  22.0     A    Male     Nagpur   72.0   India
16   117    Simran  21.0     B  Female  Hyderabad   84.0   India
17   118    Deepak  23.0     C    Male      Delhi   69.0   India
18   119     Meena  22.0     A  Female     Mumbai   87.0   India
19   120     Akash  21.0     B    Male       Pune   75.0   India
20   121      Ajay  20.0     C    Male  Hyderabad   81.0   India
21   122    Nikita  22.0     A  Female     Mumbai   92.0   India
22   123     Sumit  21.0     B    Male       Pune   77.0   India
23   124     Aarti  23.0     C  Female      Delhi   83.0   India
24   125    Ramesh  22.0     A    Male     Nagpur   70.0   India
25   126     Komal  20.0     B  Female  Hyderabad   89.0   India
26   127     Harsh  21.0     C    Male     Mumbai   85.0   India
27   128     Divya  22.0     A  Female       Pune   94.0   India
28   129     Nitin  23.0     B    Male      Delhi   71.0   India
29   130    Shreya  20.0     C  Female     Nagpur   90.0   India
30   131     Vinay  21.0     A    Male  Hyderabad   76.0   India
31   132     Payal  22.0     B  Female     Mumbai   88.0   India
32   133     Sagar  23.0     C    Male       Pune   79.0   India
33   134     Tanvi  20.0     A  Female      Delhi   91.0   India
34   135    Manish  22.0     B    Male     Nagpur   73.0   India
35   136     Swati  21.0     C  Female  Hyderabad   84.0   India
36   137      Yash  23.0     A    Male     Mumbai   86.0   India
37   138   Pallavi  22.0     B  Female       Pune   93.0   India
38   139  Abhishek  20.0     C    Male      Delhi   68.0   India
39   140    Khushi  21.0     A  Female     Nagpur   90.0   India
40   141     Rahul  21.0     B    Male       Pune   76.0   India
41   142       NaN  22.0     C  Female     Mumbai   85.0   India
42   143    Sameer  22.0     A    Male  Hyderabad   89.0   India
43   144      Amit   NaN     B    Male      Delhi   80.0   India
44   145     Sneha  22.0     C  Female        NaN   90.0   India
45   146     Rohit  21.0     A    Male       Pune    NaN   India
46   147    Anjali  20.0     B  Female  Hyderabad   85.0   India
47   148     Karan  23.0     C    Male      Delhi   67.0   India
48   149     Pooja  22.0     A  Female     Mumbai   91.0   India
49   150     Vikas  21.0     B    Male     Nagpur   74.0   India

In [92]:
#Module 6
# Practice Questions
# rename()
# Rename Marks to Score.
print()
print(df.rename(columns={"Marks":"Score"}))
# Rename Name to Student_Name.
print()
print(df.rename(columns={"Name":"Student_Name"}))
# Rename both Marks and City.
print()
print(df.rename(columns={"Marks":"Score","City":"Location"}))
# insert()
# Insert a Grade column after Age.
print()
# df_grade=df.insert(3,"Grade",['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A',
#  'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B',
#  'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C',
#  'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A',
#  'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B'])
# #print(df_grade)
# # Insert a Country column at the end of the DataFrame.
# df_country=df.insert(8,"Country",["India"] * 50)
#print(df_country)
# assign()
# Add a Result column with the value "Pass" for all students.
# print(df.assign(Result="Pass"))
# Add a Section column.
# print(df.assign(Section="A"))
# drop()
# Remove the Age column.
print()
print(df.drop(columns=["Age"]))
# Remove the City and Gender columns together.
print()
print(df.drop(columns=["City","Gender"]))

# pop()
# Remove the Marks column and store it in a variable named marks
print()
# marks=df.pop("Marks")
# print(marks)
# set_index()
# Make Roll the index.
print()
print(df.set_index("Roll"))
# Make Name the index.
print()
print(df.set_index("Name"))
# reset_index()
# Restore the default index after setting Roll as the index.
print()
print(df.reset_index())
# Set Name as the index, then reset it
print()
print(df.set_index("Name"))
# Compare the output before and after using set_index() and reset_index().
print()
print(df.set_index("Name"))
print()
print(df.reset_index())

    Roll      Name   Age Grade  Gender       City Country
0    101    Sameer  22.0     A    Male  Hyderabad   India
1    102     Rahul  21.0     B    Male       Pune   India
2    103     Priya  20.0     C  Female     Mumbai   India
3    104      Amit  23.0     A    Male      Delhi   India
4    105     Sneha  22.0     B  Female     Nagpur   India
5    106     Rohit  21.0     C    Male       Pune   India
6    107    Anjali  20.0     A  Female  Hyderabad   India
7    108     Karan  23.0     B    Male      Delhi   India
8    109     Pooja  22.0     C  Female     Mumbai   India
9    110     Vikas  21.0     A    Male     Nagpur   India
10   111      Neha  20.0     B  Female       Pune   India
11   112     Arjun  22.0     C    Male  Hyderabad   India
12   113    Kavita  21.0     A  Female      Delhi   India
13   114    Sachin  23.0     B    Male     Mumbai   India
14   115      Riya  20.0     C  Female       Pune   India
15   116     Mohan  22.0     A    Male     Nagpur   India
16   117    Simran  21.0     B  Female  Hyderabad   India
17   118    Deepak  23.0     C    Male      Delhi   India
18   119     Meena  22.0     A  Female     Mumbai   India
19   120     Akash  21.0     B    Male       Pune   India
20   121      Ajay  20.0     C    Male  Hyderabad   India
21   122    Nikita  22.0     A  Female     Mumbai   India
22   123     Sumit  21.0     B    Male       Pune   India
23   124     Aarti  23.0     C  Female      Delhi   India
24   125    Ramesh  22.0     A    Male     Nagpur   India
25   126     Komal  20.0     B  Female  Hyderabad   India
26   127     Harsh  21.0     C    Male     Mumbai   India
27   128     Divya  22.0     A  Female       Pune   India
28   129     Nitin  23.0     B    Male      Delhi   India
29   130    Shreya  20.0     C  Female     Nagpur   India
30   131     Vinay  21.0     A    Male  Hyderabad   India
31   132     Payal  22.0     B  Female     Mumbai   India
32   133     Sagar  23.0     C    Male       Pune   India
33   134     Tanvi  20.0     A  Female      Delhi   India
34   135    Manish  22.0     B    Male     Nagpur   India
35   136     Swati  21.0     C  Female  Hyderabad   India
36   137      Yash  23.0     A    Male     Mumbai   India
37   138   Pallavi  22.0     B  Female       Pune   India
38   139  Abhishek  20.0     C    Male      Delhi   India
39   140    Khushi  21.0     A  Female     Nagpur   India
40   141     Rahul  21.0     B    Male       Pune   India
41   142       NaN  22.0     C  Female     Mumbai   India
42   143    Sameer  22.0     A    Male  Hyderabad   India
43   144      Amit   NaN     B    Male      Delhi   India
44   145     Sneha  22.0     C  Female        NaN   India
45   146     Rohit  21.0     A    Male       Pune   India
46   147    Anjali  20.0     B  Female  Hyderabad   India
47   148     Karan  23.0     C    Male      Delhi   India
48   149     Pooja  22.0     A  Female     Mumbai   India
49   150     Vikas  21.0     B    Male     Nagpur   India

    Roll Student_Name   Age Grade  Gender       City Country
0    101       Sameer  22.0     A    Male  Hyderabad   India
1    102        Rahul  21.0     B    Male       Pune   India
2    103        Priya  20.0     C  Female     Mumbai   India
3    104         Amit  23.0     A    Male      Delhi   India
4    105        Sneha  22.0     B  Female     Nagpur   India
5    106        Rohit  21.0     C    Male       Pune   India
6    107       Anjali  20.0     A  Female  Hyderabad   India
7    108        Karan  23.0     B    Male      Delhi   India
8    109        Pooja  22.0     C  Female     Mumbai   India
9    110        Vikas  21.0     A    Male     Nagpur   India
10   111         Neha  20.0     B  Female       Pune   India
11   112        Arjun  22.0     C    Male  Hyderabad   India
12   113       Kavita  21.0     A  Female      Delhi   India
13   114       Sachin  23.0     B    Male     Mumbai   India
14   115         Riya  20.0     C  Female       Pune   India
15   116        Mohan  22.0     A    Male     Nagpur   India
16   117       Simran  21.0     B  Female  Hyderabad   India
17   118       Deepak  23.0     C    Male      Delhi   India
18   119        Meena  22.0     A  Female     Mumbai   India
19   120        Akash  21.0     B    Male       Pune   India
20   121         Ajay  20.0     C    Male  Hyderabad   India
21   122       Nikita  22.0     A  Female     Mumbai   India
22   123        Sumit  21.0     B    Male       Pune   India
23   124        Aarti  23.0     C  Female      Delhi   India
24   125       Ramesh  22.0     A    Male     Nagpur   India
25   126        Komal  20.0     B  Female  Hyderabad   India
26   127        Harsh  21.0     C    Male     Mumbai   India
27   128        Divya  22.0     A  Female       Pune   India
28   129        Nitin  23.0     B    Male      Delhi   India
29   130       Shreya  20.0     C  Female     Nagpur   India
30   131        Vinay  21.0     A    Male  Hyderabad   India
31   132        Payal  22.0     B  Female     Mumbai   India
32   133        Sagar  23.0     C    Male       Pune   India
33   134        Tanvi  20.0     A  Female      Delhi   India
34   135       Manish  22.0     B    Male     Nagpur   India
35   136        Swati  21.0     C  Female  Hyderabad   India
36   137         Yash  23.0     A    Male     Mumbai   India
37   138      Pallavi  22.0     B  Female       Pune   India
38   139     Abhishek  20.0     C    Male      Delhi   India
39   140       Khushi  21.0     A  Female     Nagpur   India
40   141        Rahul  21.0     B    Male       Pune   India
41   142          NaN  22.0     C  Female     Mumbai   India
42   143       Sameer  22.0     A    Male  Hyderabad   India
43   144         Amit   NaN     B    Male      Delhi   India
44   145        Sneha  22.0     C  Female        NaN   India
45   146        Rohit  21.0     A    Male       Pune   India
46   147       Anjali  20.0     B  Female  Hyderabad   India
47   148        Karan  23.0     C    Male      Delhi   India
48   149        Pooja  22.0     A  Female     Mumbai   India
49   150        Vikas  21.0     B    Male     Nagpur   India

    Roll      Name   Age Grade  Gender   Location Country
0    101    Sameer  22.0     A    Male  Hyderabad   India
1    102     Rahul  21.0     B    Male       Pune   India
2    103     Priya  20.0     C  Female     Mumbai   India
3    104      Amit  23.0     A    Male      Delhi   India
4    105     Sneha  22.0     B  Female     Nagpur   India
5    106     Rohit  21.0     C    Male       Pune   India
6    107    Anjali  20.0     A  Female  Hyderabad   India
7    108     Karan  23.0     B    Male      Delhi   India
8    109     Pooja  22.0     C  Female     Mumbai   India
9    110     Vikas  21.0     A    Male     Nagpur   India
10   111      Neha  20.0     B  Female       Pune   India
11   112     Arjun  22.0     C    Male  Hyderabad   India
12   113    Kavita  21.0     A  Female      Delhi   India
13   114    Sachin  23.0     B    Male     Mumbai   India
14   115      Riya  20.0     C  Female       Pune   India
15   116     Mohan  22.0     A    Male     Nagpur   India
16   117    Simran  21.0     B  Female  Hyderabad   India
17   118    Deepak  23.0     C    Male      Delhi   India
18   119     Meena  22.0     A  Female     Mumbai   India
19   120     Akash  21.0     B    Male       Pune   India
20   121      Ajay  20.0     C    Male  Hyderabad   India
21   122    Nikita  22.0     A  Female     Mumbai   India
22   123     Sumit  21.0     B    Male       Pune   India
23   124     Aarti  23.0     C  Female      Delhi   India
24   125    Ramesh  22.0     A    Male     Nagpur   India
25   126     Komal  20.0     B  Female  Hyderabad   India
26   127     Harsh  21.0     C    Male     Mumbai   India
27   128     Divya  22.0     A  Female       Pune   India
28   129     Nitin  23.0     B    Male      Delhi   India
29   130    Shreya  20.0     C  Female     Nagpur   India
30   131     Vinay  21.0     A    Male  Hyderabad   India
31   132     Payal  22.0     B  Female     Mumbai   India
32   133     Sagar  23.0     C    Male       Pune   India
33   134     Tanvi  20.0     A  Female      Delhi   India
34   135    Manish  22.0     B    Male     Nagpur   India
35   136     Swati  21.0     C  Female  Hyderabad   India
36   137      Yash  23.0     A    Male     Mumbai   India
37   138   Pallavi  22.0     B  Female       Pune   India
38   139  Abhishek  20.0     C    Male      Delhi   India
39   140    Khushi  21.0     A  Female     Nagpur   India
40   141     Rahul  21.0     B    Male       Pune   India
41   142       NaN  22.0     C  Female     Mumbai   India
42   143    Sameer  22.0     A    Male  Hyderabad   India
43   144      Amit   NaN     B    Male      Delhi   India
44   145     Sneha  22.0     C  Female        NaN   India
45   146     Rohit  21.0     A    Male       Pune   India
46   147    Anjali  20.0     B  Female  Hyderabad   India
47   148     Karan  23.0     C    Male      Delhi   India
48   149     Pooja  22.0     A  Female     Mumbai   India
49   150     Vikas  21.0     B    Male     Nagpur   India


    Roll      Name Grade  Gender       City Country
0    101    Sameer     A    Male  Hyderabad   India
1    102     Rahul     B    Male       Pune   India
2    103     Priya     C  Female     Mumbai   India
3    104      Amit     A    Male      Delhi   India
4    105     Sneha     B  Female     Nagpur   India
5    106     Rohit     C    Male       Pune   India
6    107    Anjali     A  Female  Hyderabad   India
7    108     Karan     B    Male      Delhi   India
8    109     Pooja     C  Female     Mumbai   India
9    110     Vikas     A    Male     Nagpur   India
10   111      Neha     B  Female       Pune   India
11   112     Arjun     C    Male  Hyderabad   India
12   113    Kavita     A  Female      Delhi   India
13   114    Sachin     B    Male     Mumbai   India
14   115      Riya     C  Female       Pune   India
15   116     Mohan     A    Male     Nagpur   India
16   117    Simran     B  Female  Hyderabad   India
17   118    Deepak     C    Male      Delhi   India
18   119     Meena     A  Female     Mumbai   India
19   120     Akash     B    Male       Pune   India
20   121      Ajay     C    Male  Hyderabad   India
21   122    Nikita     A  Female     Mumbai   India
22   123     Sumit     B    Male       Pune   India
23   124     Aarti     C  Female      Delhi   India
24   125    Ramesh     A    Male     Nagpur   India
25   126     Komal     B  Female  Hyderabad   India
26   127     Harsh     C    Male     Mumbai   India
27   128     Divya     A  Female       Pune   India
28   129     Nitin     B    Male      Delhi   India
29   130    Shreya     C  Female     Nagpur   India
30   131     Vinay     A    Male  Hyderabad   India
31   132     Payal     B  Female     Mumbai   India
32   133     Sagar     C    Male       Pune   India
33   134     Tanvi     A  Female      Delhi   India
34   135    Manish     B    Male     Nagpur   India
35   136     Swati     C  Female  Hyderabad   India
36   137      Yash     A    Male     Mumbai   India
37   138   Pallavi     B  Female       Pune   India
38   139  Abhishek     C    Male      Delhi   India
39   140    Khushi     A  Female     Nagpur   India
40   141     Rahul     B    Male       Pune   India
41   142       NaN     C  Female     Mumbai   India
42   143    Sameer     A    Male  Hyderabad   India
43   144      Amit     B    Male      Delhi   India
44   145     Sneha     C  Female        NaN   India
45   146     Rohit     A    Male       Pune   India
46   147    Anjali     B  Female  Hyderabad   India
47   148     Karan     C    Male      Delhi   India
48   149     Pooja     A  Female     Mumbai   India
49   150     Vikas     B    Male     Nagpur   India

    Roll      Name   Age Grade Country
0    101    Sameer  22.0     A   India
1    102     Rahul  21.0     B   India
2    103     Priya  20.0     C   India
3    104      Amit  23.0     A   India
4    105     Sneha  22.0     B   India
5    106     Rohit  21.0     C   India
6    107    Anjali  20.0     A   India
7    108     Karan  23.0     B   India
8    109     Pooja  22.0     C   India
9    110     Vikas  21.0     A   India
10   111      Neha  20.0     B   India
11   112     Arjun  22.0     C   India
12   113    Kavita  21.0     A   India
13   114    Sachin  23.0     B   India
14   115      Riya  20.0     C   India
15   116     Mohan  22.0     A   India
16   117    Simran  21.0     B   India
17   118    Deepak  23.0     C   India
18   119     Meena  22.0     A   India
19   120     Akash  21.0     B   India
20   121      Ajay  20.0     C   India
21   122    Nikita  22.0     A   India
22   123     Sumit  21.0     B   India
23   124     Aarti  23.0     C   India
24   125    Ramesh  22.0     A   India
25   126     Komal  20.0     B   India
26   127     Harsh  21.0     C   India
27   128     Divya  22.0     A   India
28   129     Nitin  23.0     B   India
29   130    Shreya  20.0     C   India
30   131     Vinay  21.0     A   India
31   132     Payal  22.0     B   India
32   133     Sagar  23.0     C   India
33   134     Tanvi  20.0     A   India
34   135    Manish  22.0     B   India
35   136     Swati  21.0     C   India
36   137      Yash  23.0     A   India
37   138   Pallavi  22.0     B   India
38   139  Abhishek  20.0     C   India
39   140    Khushi  21.0     A   India
40   141     Rahul  21.0     B   India
41   142       NaN  22.0     C   India
42   143    Sameer  22.0     A   India
43   144      Amit   NaN     B   India
44   145     Sneha  22.0     C   India
45   146     Rohit  21.0     A   India
46   147    Anjali  20.0     B   India
47   148     Karan  23.0     C   India
48   149     Pooja  22.0     A   India
49   150     Vikas  21.0     B   India


          Name   Age Grade  Gender       City Country
Roll
101     Sameer  22.0     A    Male  Hyderabad   India
102      Rahul  21.0     B    Male       Pune   India
103      Priya  20.0     C  Female     Mumbai   India
104       Amit  23.0     A    Male      Delhi   India
105      Sneha  22.0     B  Female     Nagpur   India
106      Rohit  21.0     C    Male       Pune   India
107     Anjali  20.0     A  Female  Hyderabad   India
108      Karan  23.0     B    Male      Delhi   India
109      Pooja  22.0     C  Female     Mumbai   India
110      Vikas  21.0     A    Male     Nagpur   India
111       Neha  20.0     B  Female       Pune   India
112      Arjun  22.0     C    Male  Hyderabad   India
113     Kavita  21.0     A  Female      Delhi   India
114     Sachin  23.0     B    Male     Mumbai   India
115       Riya  20.0     C  Female       Pune   India
116      Mohan  22.0     A    Male     Nagpur   India
117     Simran  21.0     B  Female  Hyderabad   India
118     Deepak  23.0     C    Male      Delhi   India
119      Meena  22.0     A  Female     Mumbai   India
120      Akash  21.0     B    Male       Pune   India
121       Ajay  20.0     C    Male  Hyderabad   India
122     Nikita  22.0     A  Female     Mumbai   India
123      Sumit  21.0     B    Male       Pune   India
124      Aarti  23.0     C  Female      Delhi   India
125     Ramesh  22.0     A    Male     Nagpur   India
126      Komal  20.0     B  Female  Hyderabad   India
127      Harsh  21.0     C    Male     Mumbai   India
128      Divya  22.0     A  Female       Pune   India
129      Nitin  23.0     B    Male      Delhi   India
130     Shreya  20.0     C  Female     Nagpur   India
131      Vinay  21.0     A    Male  Hyderabad   India
132      Payal  22.0     B  Female     Mumbai   India
133      Sagar  23.0     C    Male       Pune   India
134      Tanvi  20.0     A  Female      Delhi   India
135     Manish  22.0     B    Male     Nagpur   India
136      Swati  21.0     C  Female  Hyderabad   India
137       Yash  23.0     A    Male     Mumbai   India
138    Pallavi  22.0     B  Female       Pune   India
139   Abhishek  20.0     C    Male      Delhi   India
140     Khushi  21.0     A  Female     Nagpur   India
141      Rahul  21.0     B    Male       Pune   India
142        NaN  22.0     C  Female     Mumbai   India
143     Sameer  22.0     A    Male  Hyderabad   India
144       Amit   NaN     B    Male      Delhi   India
145      Sneha  22.0     C  Female        NaN   India
146      Rohit  21.0     A    Male       Pune   India
147     Anjali  20.0     B  Female  Hyderabad   India
148      Karan  23.0     C    Male      Delhi   India
149      Pooja  22.0     A  Female     Mumbai   India
150      Vikas  21.0     B    Male     Nagpur   India

          Roll   Age Grade  Gender       City Country
Name
Sameer     101  22.0     A    Male  Hyderabad   India
Rahul      102  21.0     B    Male       Pune   India
Priya      103  20.0     C  Female     Mumbai   India
Amit       104  23.0     A    Male      Delhi   India
Sneha      105  22.0     B  Female     Nagpur   India
Rohit      106  21.0     C    Male       Pune   India
Anjali     107  20.0     A  Female  Hyderabad   India
Karan      108  23.0     B    Male      Delhi   India
Pooja      109  22.0     C  Female     Mumbai   India
Vikas      110  21.0     A    Male     Nagpur   India
Neha       111  20.0     B  Female       Pune   India
Arjun      112  22.0     C    Male  Hyderabad   India
Kavita     113  21.0     A  Female      Delhi   India
Sachin     114  23.0     B    Male     Mumbai   India
Riya       115  20.0     C  Female       Pune   India
Mohan      116  22.0     A    Male     Nagpur   India
Simran     117  21.0     B  Female  Hyderabad   India
Deepak     118  23.0     C    Male      Delhi   India
Meena      119  22.0     A  Female     Mumbai   India
Akash      120  21.0     B    Male       Pune   India
Ajay       121  20.0     C    Male  Hyderabad   India
Nikita     122  22.0     A  Female     Mumbai   India
Sumit      123  21.0     B    Male       Pune   India
Aarti      124  23.0     C  Female      Delhi   India
Ramesh     125  22.0     A    Male     Nagpur   India
Komal      126  20.0     B  Female  Hyderabad   India
Harsh      127  21.0     C    Male     Mumbai   India
Divya      128  22.0     A  Female       Pune   India
Nitin      129  23.0     B    Male      Delhi   India
Shreya     130  20.0     C  Female     Nagpur   India
Vinay      131  21.0     A    Male  Hyderabad   India
Payal      132  22.0     B  Female     Mumbai   India
Sagar      133  23.0     C    Male       Pune   India
Tanvi      134  20.0     A  Female      Delhi   India
Manish     135  22.0     B    Male     Nagpur   India
Swati      136  21.0     C  Female  Hyderabad   India
Yash       137  23.0     A    Male     Mumbai   India
Pallavi    138  22.0     B  Female       Pune   India
Abhishek   139  20.0     C    Male      Delhi   India
Khushi     140  21.0     A  Female     Nagpur   India
Rahul      141  21.0     B    Male       Pune   India
NaN        142  22.0     C  Female     Mumbai   India
Sameer     143  22.0     A    Male  Hyderabad   India
Amit       144   NaN     B    Male      Delhi   India
Sneha      145  22.0     C  Female        NaN   India
Rohit      146  21.0     A    Male       Pune   India
Anjali     147  20.0     B  Female  Hyderabad   India
Karan      148  23.0     C    Male      Delhi   India
Pooja      149  22.0     A  Female     Mumbai   India
Vikas      150  21.0     B    Male     Nagpur   India

    index  Roll      Name   Age Grade  Gender       City Country
0       0   101    Sameer  22.0     A    Male  Hyderabad   India
1       1   102     Rahul  21.0     B    Male       Pune   India
2       2   103     Priya  20.0     C  Female     Mumbai   India
3       3   104      Amit  23.0     A    Male      Delhi   India
4       4   105     Sneha  22.0     B  Female     Nagpur   India
5       5   106     Rohit  21.0     C    Male       Pune   India
6       6   107    Anjali  20.0     A  Female  Hyderabad   India
7       7   108     Karan  23.0     B    Male      Delhi   India
8       8   109     Pooja  22.0     C  Female     Mumbai   India
9       9   110     Vikas  21.0     A    Male     Nagpur   India
10     10   111      Neha  20.0     B  Female       Pune   India