In [21]:
import pandas as pd
df=pd.read_csv("C:\\Users\\hp\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

##### Pandas Challenges (Based on Your Notebook)
##### Challenge 1 – Complete Data Cleaning
##### Your manager gives you a messy dataset.
##### Perform all of the following:
##### • Load the dataset.
##### • Display dataset information.
##### • Find missing values.
##### • Remove duplicate rows.
##### • Fill missing values:
##### o Age → median
##### o Balance → mean
##### • Rename:
##### o Target → CustomerStatus
##### o AnnualIncome → Income
##### • Display the first 15 rows.
##### Methods expected:
##### read_csv()
##### info()
##### isnull()
##### drop_duplicates()
##### median()
##### mean()
##### fillna()
##### rename()
##### head()

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [23]:
df.isnull()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1015,False,False,False,False,False,False,False,False,False,False,False
1016,False,False,False,False,False,False,False,False,True,False,False
1017,False,False,False,False,False,False,False,False,False,False,False
1018,False,False,True,False,False,False,False,False,False,False,False
1019,False,False,False,False,False,True,False,False,False,True,False

In [24]:
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [25]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [26]:
df=df.rename(columns={"Target":"Customer","AnnualIncome":"Income"})
df

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

##### Challenge 2 – Banking Report
##### The bank wants a numeric report.
##### Tasks
##### • Select only numeric columns.
##### • Display summary statistics.
##### • Convert Age and CreditScore to float.
##### • Display information again.

In [30]:
df.select_dtypes(include=["number"])

      CustomerID   Age    Income  Spending  CreditScore        Balance  Tenure
0          10001  58.0   49184.0      2139          581   97523.535666       2
1          10002  65.0  162964.0      6197          732    6356.540000       1
2          10003  56.0   26956.0     37281          503  143203.920000       8
3          10004  55.0   92926.0       925          463  139627.880000       5
4          10005  66.0  108236.0      7198          394   75985.460000       5
...          ...   ...       ...       ...          ...            ...     ...
1015       10450  43.0  173620.0      7121          644   60353.030000       2
1016       10753  25.0   54490.0     13794          303  124512.070000       4
1017       10810  49.0   82062.0     47170          813   53850.090000       8
1018       10267  38.0       NaN     10424          722  138100.050000       6
1019       10059  62.0   97504.0     36833          430   97523.535666      10

[1020 rows x 7 columns]

In [31]:
df.describe()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,967.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,52303.362541,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,66149.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,158000.500000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [32]:
df[["Age","CreditScore"]]=df[["Age","CreditScore"]].astype(float)
df[["Age","CreditScore"]]

       Age  CreditScore
0     58.0        581.0
1     65.0        732.0
2     56.0        503.0
3     55.0        463.0
4     66.0        394.0
...    ...          ...
1015  43.0        644.0
1016  25.0        303.0
1017  49.0        813.0
1018  38.0        722.0
1019  62.0        430.0

[1020 rows x 2 columns]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   1020 non-null   int64
 1   Age          1020 non-null   float64
 2   Income       967 non-null    float64
 3   Spending     1020 non-null   int64
 4   CreditScore  1020 non-null   float64
 5   Balance      1020 non-null   float64
 6   Tenure       1020 non-null   int64
 7   Geography    969 non-null    object
 8   Gender       968 non-null    object
 9   Segment      969 non-null    object
 10  Customer     1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

##### Challenge 3 – Duplicate Investigation
##### Find duplicate customers.
##### Then
##### • Count duplicate rows.
##### • Remove duplicates.
##### • Print information before and after removing duplicates.
##### • Show the last 20 rows.

In [35]:
df.duplicated().sum()

np.int64(20)

In [36]:
df.drop_duplicates()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,NaN,Stay

In [38]:
print("Before Removing")
print(df)
print("After Removing")
print()
print(df.drop_duplicates())

Before Removing
      CustomerID   Age    Income  Spending  CreditScore        Balance  \
0          10001  58.0   49184.0      2139        581.0   97523.535666
1          10002  65.0  162964.0      6197        732.0    6356.540000
2          10003  56.0   26956.0     37281        503.0  143203.920000
3          10004  55.0   92926.0       925        463.0  139627.880000
4          10005  66.0  108236.0      7198        394.0   75985.460000
...          ...   ...       ...       ...          ...            ...
1015       10450  43.0  173620.0      7121        644.0   60353.030000
1016       10753  25.0   54490.0     13794        303.0  124512.070000
1017       10810  49.0   82062.0     47170        813.0   53850.090000
1018       10267  38.0       NaN     10424        722.0  138100.050000
1019       10059  62.0   97504.0     36833        430.0   97523.535666

      Tenure Geography  Gender    Segment Customer
0          2    France    Male        SME     Stay
1          1       USA    Male        SME    Churn
2          8    Canada    Male  Corporate     Stay
3          5       NaN    Male     Retail    Churn
4          5        UK   Other  Corporate    Churn
...      ...       ...     ...        ...      ...
1015       2       USA   Other  Corporate     Stay
1016       4     India     NaN  Corporate    Churn
1017       8   Germany  Female     Retail     Stay
1018       6   Germany   Other  Corporate     Stay
1019      10    Canada   Other        NaN    Churn

[1020 rows x 11 columns]
After Removing

     CustomerID   Age    Income  Spending  CreditScore        Balance  Tenure  \
0         10001  58.0   49184.0      2139        581.0   97523.535666       2
1         10002  65.0  162964.0      6197        732.0    6356.540000       1
2         10003  56.0   26956.0     37281        503.0  143203.920000       8
3         10004  55.0   92926.0       925        463.0  139627.880000       5
4         10005  66.0  108236.0      7198        394.0   75985.460000       5
..          ...   ...       ...       ...          ...            ...     ...
995       10996  34.0   81731.0     40980        761.0  181465.650000       5
996       10997  47.0   42475.0      1176        780.0   26640.990000       5
997       10998  31.0  120531.0     46929        733.0  147220.820000       4
998       10999  21.0   33661.0     22314        540.0   94186.480000       5
999       11000  63.0   31930.0       851        559.0  100908.400000       6

    Geography  Gender    Segment Customer
0      France    Male        SME     Stay
1         USA    Male        SME    Churn
2      Canada    Male  Corporate     Stay
3         NaN    Male     Retail    Churn
4          UK   Other  Corporate    Churn
..        ...     ...        ...      ...
995   Germany   Other        SME     Stay
996    France  Female        SME     Stay
997     India    Male        SME     Stay
998       NaN   Other        SME     Stay
999        UK  Female        NaN     Stay

[1000 rows x 11 columns]

In [39]:
df.tail(20)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer
1000,10643,41.0,125012.0,18825,761.0,35977.850000,2,Germany,Other,Retail,Stay
1001,10763,56.0,102965.0,17517,838.0,115028.540000,9,UK,NaN,SME,Stay
1002,10910,66.0,118506.0,6296,306.0,81892.130000,4,Canada,Male,SME,Churn
1003,10200,19.0,115052.0,20741,484.0,190233.860000,5,Canada,Male,Retail,Churn
1004,10587,29.0,NaN,40255,383.0,168358.600000,2,Germany,Male,Corporate,Churn
1005,10798,22.0,176830.0,7626,688.0,65481.650000,10,France,Male,Retail,Stay
1006,10653,32.0,NaN,21266,598.0,142086.700000,9,France,Female,Corporate,Stay
1007,10756,53.0,74430.0,3705,489.0,29651.230000,10,UK,Male,Retail,Churn
1008,10417,70.0,40417.0,37956,681.0,23880.190000,10,India,Male,Retail,Stay
1009,10499,34.0,166546.0,12497,643.0,130886.930000,3,UK,Male,SME,Stay
1010,10515,62.0,199762.0,41808,309.0,60223.290000,10,India,Other,SME,Churn
1011,10457,44.0,63604.0,27633,804.0,176354.130000,5,Germany,Female,Retail,Stay
1012,10882,61.0,115417.0,3879,413.0,76591.000000,7,NaN,Male,Corporate,Churn
1013,10531,64.0,85162.0,32083,654.0,132742.130000,10,Canada,Male,SME,Stay
1014,10181,50.0,166466.0,44281,662.0,14415.100000,0,Canada,Male,Corporate,Churn
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

#### Challenge 4 – HR Department
#### HR wants better column names.
#### Rename
#### CustomerID → Employee_ID
#### Age → EmployeeAge
#### Gender → EmployeeGender
#### AnnualIncome → Salary
#### Target → PromotionStatus
#### Then
#### • Add prefix
#### HR_
#### to every column.
#### Display 10 random records.

In [41]:
df.rename(columns={
    "CustomerID":"Employee_ID",
    "Age":"EmployeeAge",
    "Gender":"EmployeeGender",
    "AnnualIncome":"Salary",
    "Target":"PromotionStatus"
}, inplace=True)

print(df.head())

   Employee_ID  EmployeeAge    Income  Spending  CreditScore        Balance  \
0        10001         58.0   49184.0      2139        581.0   97523.535666
1        10002         65.0  162964.0      6197        732.0    6356.540000
2        10003         56.0   26956.0     37281        503.0  143203.920000
3        10004         55.0   92926.0       925        463.0  139627.880000
4        10005         66.0  108236.0      7198        394.0   75985.460000

   Tenure Geography EmployeeGender    Segment Customer
0       2    France           Male        SME     Stay
1       1       USA           Male        SME    Churn
2       8    Canada           Male  Corporate     Stay
3       5       NaN           Male     Retail    Churn
4       5        UK          Other  Corporate    Churn

In [42]:
df = df.add_prefix("HR_")
print(df.head())

   HR_Employee_ID  HR_EmployeeAge  HR_Income  HR_Spending  HR_CreditScore  \
0           10001            58.0    49184.0         2139           581.0
1           10002            65.0   162964.0         6197           732.0
2           10003            56.0    26956.0        37281           503.0
3           10004            55.0    92926.0          925           463.0
4           10005            66.0   108236.0         7198           394.0

      HR_Balance  HR_Tenure HR_Geography HR_EmployeeGender HR_Segment  \
0   97523.535666          2       France              Male        SME
1    6356.540000          1          USA              Male        SME
2  143203.920000          8       Canada              Male  Corporate
3  139627.880000          5          NaN              Male     Retail
4   75985.460000          5           UK             Other  Corporate

  HR_Customer
0        Stay
1       Churn
2        Stay
3       Churn
4       Churn

In [43]:
print(df.sample(10))

     HR_Employee_ID  HR_EmployeeAge  HR_Income  HR_Spending  HR_CreditScore  \
136           10137            34.0   139756.0        20299           503.0
495           10496            44.0   126063.0        25945           336.0
968           10969            35.0    95247.0        42839           464.0
376           10377            66.0   135701.0        36305           523.0
176           10177            44.0    76510.0        49975           824.0
201           10202            51.0    29895.0        43880           644.0
222           10223            70.0   162352.0        31524           559.0
902           10903            40.0    44243.0        21888           356.0
62            10063            23.0    81569.0        44592           617.0
788           10789            70.0   142755.0         6874           766.0

     HR_Balance  HR_Tenure HR_Geography HR_EmployeeGender HR_Segment  \
136   199874.71          7        India              Male        NaN
495   116604.74          9          USA            Female        SME
968    51289.33          9          NaN            Female     Retail
376   197955.15          1       France             Other     Retail
176    22763.50          6        India            Female        SME
201   175278.55          9          USA             Other  Corporate
222     7324.15         10          USA            Female  Corporate
902   121630.24          3      Germany             Other     Retail
62     44928.13          3          USA              Male     Retail
788    62078.34         10       France            Female  Corporate

    HR_Customer
136        Stay
495       Churn
968       Churn
376       Churn
176        Stay
201        Stay
222       Churn
902       Churn
62         Stay
788        Stay

##### Challenge 5 – Finance Cleaning
##### Finance department reports missing values.
##### Tasks
##### Fill
##### AnnualIncome → Median
##### Balance → Mean
##### Age → Median
##### Then
##### Generate descriptive statistics.

In [50]:
df["HR_Income"] = df["HR_Income"].fillna(df["HR_Income"].median())
df["HR_EmployeeAge"] = df["HR_EmployeeAge"].fillna(df["HR_EmployeeAge"].median())
df["HR_Balance"] = df["HR_Balance"].fillna(df["HR_Balance"].mean())
df

,HR_Employee_ID,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_Customer,AnnualIncome
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay,49184.0
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn,162964.0
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay,26956.0
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn,92926.0
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn,108236.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay,173620.0
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn,54490.0
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay,82062.0
1018,10267,38.0,112358.0,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay,112358.0
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn,97504.0

In [52]:
df.describe()
df

,HR_Employee_ID,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_Customer,AnnualIncome
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay,49184.0
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn,162964.0
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay,26956.0
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn,92926.0
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn,108236.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay,173620.0
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn,54490.0
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay,82062.0
1018,10267,38.0,112358.0,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay,112358.0
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn,97504.0

##### Challenge 6 – Data Type Audit
##### The company says
##### Age and AnnualIncome are stored incorrectly.
##### Tasks
##### Convert
##### Age → int
##### AnnualIncome → float
##### Balance → float
##### Target → string
##### Print information.

In [54]:
print(df.astype({"HR_EmployeeAge":int,"AnnualIncome":float,"HR_Balance":float,"HR_Customer":str}))

      HR_Employee_ID  HR_EmployeeAge  HR_Income  HR_Spending  HR_CreditScore  \
0              10001              58    49184.0         2139           581.0
1              10002              65   162964.0         6197           732.0
2              10003              56    26956.0        37281           503.0
3              10004              55    92926.0          925           463.0
4              10005              66   108236.0         7198           394.0
...              ...             ...        ...          ...             ...
1015           10450              43   173620.0         7121           644.0
1016           10753              25    54490.0        13794           303.0
1017           10810              49    82062.0        47170           813.0
1018           10267              38   112358.0        10424           722.0
1019           10059              62    97504.0        36833           430.0

         HR_Balance  HR_Tenure HR_Geography HR_EmployeeGender HR_Segment  \
0      97523.535666          2       France              Male        SME
1       6356.540000          1          USA              Male        SME
2     143203.920000          8       Canada              Male  Corporate
3     139627.880000          5          NaN              Male     Retail
4      75985.460000          5           UK             Other  Corporate
...             ...        ...          ...               ...        ...
1015   60353.030000          2          USA             Other  Corporate
1016  124512.070000          4        India               NaN  Corporate
1017   53850.090000          8      Germany            Female     Retail
1018  138100.050000          6      Germany             Other  Corporate
1019   97523.535666         10       Canada             Other        NaN

     HR_Customer  AnnualIncome
0           Stay       49184.0
1          Churn      162964.0
2           Stay       26956.0
3          Churn       92926.0
4          Churn      108236.0
...          ...           ...
1015        Stay      173620.0
1016       Churn       54490.0
1017        Stay       82062.0
1018        Stay      112358.0
1019       Churn       97504.0

[1020 rows x 12 columns]

##### Challenge 7 – Customer Analytics
##### Create a new DataFrame that
##### • removes Segment
##### • removes Geography
##### • removes duplicate rows
##### Display
##### • first 10 rows
##### • dataset information
##### • statistical summary

In [59]:
new_df=df.drop(columns=["HR_Segment","HR_Geography"])
new_df=new_df.drop_duplicates()
print(new_dataframe.head(10))

   HR_Employee_ID  HR_EmployeeAge  HR_Income  HR_Spending  HR_CreditScore  \
0           10001            58.0    49184.0         2139           581.0
1           10002            65.0   162964.0         6197           732.0
2           10003            56.0    26956.0        37281           503.0
3           10004            55.0    92926.0          925           463.0
4           10005            66.0   108236.0         7198           394.0
5           10006            69.0    31390.0        48323           770.0
6           10007            58.0   182141.0        24200           891.0
7           10008            67.0    95861.0         5729           538.0
8           10009            41.0    62638.0        24760           663.0
9           10010            22.0   179680.0        42113           475.0

      HR_Balance  HR_Tenure HR_EmployeeGender HR_Customer  AnnualIncome
0   97523.535666          2              Male        Stay       49184.0
1    6356.540000          1              Male       Churn      162964.0
2  143203.920000          8              Male        Stay       26956.0
3  139627.880000          5              Male       Churn       92926.0
4   75985.460000          5             Other       Churn      108236.0
5  107245.620000          6             Other        Stay       31390.0
6   38457.720000          1             Other       Churn      182141.0
7  173296.730000          6            Female        Stay       95861.0
8   41901.410000          4             Other        Stay       62638.0
9  106827.980000          3            Female       Churn      179680.0

In [61]:
print(new_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   HR_Employee_ID     1000 non-null   int64
 1   HR_EmployeeAge     1000 non-null   float64
 2   HR_Income          1000 non-null   float64
 3   HR_Spending        1000 non-null   int64
 4   HR_CreditScore     1000 non-null   float64
 5   HR_Balance         1000 non-null   float64
 6   HR_Tenure          1000 non-null   int64
 7   HR_EmployeeGender  950 non-null    object
 8   HR_Customer        1000 non-null   object
 9   AnnualIncome       1000 non-null   float64
dtypes: float64(5), int64(3), object(2)
memory usage: 85.9+ KB
None

In [62]:
print(new_df.describe())

       HR_Employee_ID  HR_EmployeeAge      HR_Income   HR_Spending  \
count     1000.000000     1000.000000    1000.000000   1000.000000
mean     10500.500000       44.202000  112453.288000  25285.558000
std        288.819436       15.130834   51081.479931  14211.735656
min      10001.000000       18.000000   20227.000000    537.000000
25%      10250.750000       31.000000   68437.250000  13213.000000
50%      10500.500000       44.000000  112358.000000  24901.000000
75%      10750.250000       57.000000  155570.750000  37960.250000
max      11000.000000       70.000000  199967.000000  49995.000000

       HR_CreditScore     HR_Balance    HR_Tenure   AnnualIncome
count     1000.000000    1000.000000  1000.000000    1000.000000
mean       603.088000   97555.864273     5.241000  112453.288000
std        176.605486   54430.062511     3.179155   51081.479931
min        300.000000     547.600000     0.000000   20227.000000
25%        441.000000   52074.240000     2.000000   68437.250000
50%        606.500000   97523.535666     5.000000  112358.000000
75%        758.250000  142297.910000     8.000000  155570.750000
max        900.000000  199885.880000    10.000000  199967.000000

##### Challenge 8 – ML Dataset Preparation
##### Prepare a machine learning dataset.
##### Perform
##### • Remove duplicates
##### • Remove CustomerID
##### • Remove Segment
##### • Fill missing values
##### • Rename Target to Output
##### Finally
##### Display
##### head()
##### info()
##### describe()
##### value_counts(Output)

In [68]:
new_df=df.drop_duplicates()
new_df=new_df.drop(columns=["HR_Employee_ID","HR_Segment"])
new_df=new_df.fillna(0)
new_df=new_df.rename(columns={"HR_Customer":"HR_Output"})
new_df

,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Output,AnnualIncome
0,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,Stay,49184.0
1,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,Churn,162964.0
2,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Stay,26956.0
3,55.0,92926.0,925,463.0,139627.880000,5,0,Male,Churn,92926.0
4,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Churn,108236.0
...,...,...,...,...,...,...,...,...,...,...
995,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,Stay,81731.0
996,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,Stay,42475.0
997,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,Stay,120531.0
998,21.0,33661.0,22314,540.0,94186.480000,5,0,Other,Stay,33661.0
999,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,Stay,31930.0

In [69]:
new_df.head()

,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Output,AnnualIncome
0,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,Stay,49184.0
1,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,Churn,162964.0
2,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Stay,26956.0
3,55.0,92926.0,925,463.0,139627.880000,5,0,Male,Churn,92926.0
4,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Churn,108236.0

In [70]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   HR_EmployeeAge     1000 non-null   float64
 1   HR_Income          1000 non-null   float64
 2   HR_Spending        1000 non-null   int64
 3   HR_CreditScore     1000 non-null   float64
 4   HR_Balance         1000 non-null   float64
 5   HR_Tenure          1000 non-null   int64
 6   HR_Geography       1000 non-null   object
 7   HR_EmployeeGender  1000 non-null   object
 8   HR_Output          1000 non-null   object
 9   AnnualIncome       1000 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 85.9+ KB

In [71]:
new_df.describe()

,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,AnnualIncome
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.202000,112453.288000,25285.558000,603.088000,97555.864273,5.241000,112453.288000
std,15.130834,51081.479931,14211.735656,176.605486,54430.062511,3.179155,51081.479931
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,20227.000000
25%,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000,68437.250000
50%,44.000000,112358.000000,24901.000000,606.500000,97523.535666,5.000000,112358.000000
75%,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000,155570.750000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,199967.000000

In [76]:
new_df["HR_Output"].value_counts()

HR_Output
Churn    506
Stay     494
Name: count, dtype: int64

##### Challenge 9 – Column Transformation
##### Create these new columns
##### NetWorth = Balance + AnnualIncome
##### AgeAfterRetirement = Age + 20
##### DoubleCreditScore = CreditScore * 2
##### IncomePerMonth = AnnualIncome / 12
##### Then
##### Display first 15 rows.

In [77]:
df

,HR_Employee_ID,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_Customer,AnnualIncome
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay,49184.0
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn,162964.0
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay,26956.0
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn,92926.0
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn,108236.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay,173620.0
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn,54490.0
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay,82062.0
1018,10267,38.0,112358.0,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay,112358.0
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn,97504.0

In [80]:
df["Net_worth"]=df["HR_Balance"]+df["AnnualIncome"]
df["AgeAfterRetirement"]=df["HR_EmployeeAge"]+20
df["DoubleCreditScore"]=df["HR_CreditScore"]*2
df["IncomePerMonth"]=df["AnnualIncome"]/12
df.