##### Pandas + NumPy Data Cleaning — 30 Questions
##### 
##### 1. Load the CSV using Pandas and display the first 10 rows.

In [105]:
import pandas as pd
df=pd.read_csv("C:\\Users\\hp\\Downloads\\customer_data - customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

##### 2. Check the number of rows and columns in the dataset.

In [106]:
print("Rows=",df.shape[0])
print("Columns=",df.shape[1])

Rows= 2000
Columns= 15

##### 3. Display all column names and identify which column names contain
##### leading/trailing spaces or inconsistent capitalization.

In [107]:
df.columns

Index(['Customer ID', 'Age', 'income_usd', 'credit Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

##### 4. Check the data type of every column using Pandas.

In [108]:
print(df.dtypes)

Customer ID          object
Age                  object
income_usd           object
credit Score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

##### 5. Calculate the number and percentage of missing values in every column.

In [109]:
print("Number of Missing values=",df.isnull().sum())
print()
print("Percentage of each column=\n",(df.isnull().sum()/len(df))*100)

Number of Missing values= Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

Percentage of each column=
 Customer ID          1.00
Age                 16.55
income_usd          22.00
credit Score        18.00
tenure_years        12.90
monthly_visits      14.00
satisfaction        19.95
City                15.00
customer_segment    19.00
gender              12.00
is_active           17.00
churn_flag           8.00
signup_date         12.00
lead_source         21.00
notes_text          32.80
dtype: float64

##### 6. Find the rows where Customer ID is missing.

In [110]:
df[df["Customer ID"].isnull()]

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
162,NaN,18,61780.99213,715.4452325,10.137001,5.0,3.179153,Delhi,UNKNOWN,Female,NaN,No,2021-04-22,website,follow-up needed
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

##### 7. Remove leading/trailing whitespace from all column names and convert them
##### to lowercase with underscores.

In [111]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

##### 8. Identify duplicate Customer ID values and count how many duplicates exist.

In [112]:
df["customer_id"].duplicated().value_counts()

customer_id
False    1981
True       19
Name: count, dtype: int64

##### 9. Remove duplicate customer records while keeping the first occurrence.

In [113]:
df.drop_duplicates()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

##### 10.Find all unique values in the customer_segment column and identify
##### inconsistent categories such as Consumer, consumer, consumer , etc.

In [114]:
df["customer_segment"].unique()

array(['consumer', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

##### 11.Clean the customer_segment column by standardizing capitalization and
##### whitespace.

In [115]:
df["customer_segment"]=df["customer_segment"].str.strip().str.title()
df["customer_segment"]

0         Consumer
1         Consumer
2         Consumer
3       Enterprise
4       Enterprise
           ...
1995      Consumer
1996           Smb
1997          Smb.
1998           Smb
1999      Consumer
Name: customer_segment, Length: 2000, dtype: object

##### 12.Find all unique values in the gender column and convert them into consistent
##### categories such as Male and Female.

In [116]:
df["gender"].unique()
df["gender"] = df["gender"].str.strip().str.lower()

df["gender"] = df["gender"].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"})
df["gender"]

0          NaN
1         Male
2         Male
3         Male
4         Male
         ...
1995      Male
1996      Male
1997    Female
1998       NaN
1999       NaN
Name: gender, Length: 2000, dtype: object

##### 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and No, no, N, 0 become 0.

In [117]:
df["is_active"] = df["is_active"].astype(str).str.strip().str.lower()
df["is_active"] = df["is_active"].replace({
    "yes": 1,
    "y": 1,
    "1": 1,
    "no": 0,
    "n": 0,
    "0": 0
})
df["is_active"]

0         1
1       nan
2         1
3         0
4         1
       ...
1995      0
1996      0
1997      1
1998      0
1999      1
Name: is_active, Length: 2000, dtype: object

##### 14.Convert the churn_flag column from categorical values (Yes/No) into a binary
##### numerical column (1/0).

In [118]:
df["churn_flag"] = df["churn_flag"].astype(str).str.strip().str.lower()
df["churn_flag"] = df["churn_flag"].replace({"Yes": 1,"No": 0})
df["churn_flag"]

0        no
1        no
2        no
3        no
4        no
       ...
1995     no
1996    yes
1997     no
1998    yes
1999     no
Name: churn_flag, Length: 2000, dtype: object

##### 15.Identify all values in income_usd that cannot be directly interpreted as
##### numbers.

In [119]:
invalid_income = df[pd.to_numeric(df["income_usd"], errors="coerce").isna()]
print(invalid_income["income_usd"])

5       $44,696
10      $41,941
11          NaN
13          NaN
18          NaN
         ...
1980    $58,046
1985        NaN
1989        NaN
1990        NaN
1991        NaN
Name: income_usd, Length: 645, dtype: object

In [120]:
df["income_usd"].value_counts(dropna=False)

income_usd
NaN              440
₹55k               9
not available      9
missing            6
error              5
                ...
37624.36767        1
60918.82272        1
61907.2415         1
44710.3978         1
53723.87392        1
Name: count, Length: 1535, dtype: int64

##### 16.Clean income_usd by removing currency symbols, commas, and invalid text,
##### then convert it to a numeric column using pd.to_numeric().

In [121]:
df["income_usd"] = (
    df["income_usd"]
    .astype(str)
    .str.replace("$", "")
    .str.replace(",", "")
    .str.strip())

df["income_usd"] = pd.to_numeric(df["income_usd"], errors="coerce")
print(df["income_usd"])

0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 2000, dtype: float64

##### 17.Clean the Age column so values such as "35 years" become numeric values.

In [122]:
df["age"] = df["age"].str.extract("(\d+)").astype("Int64")
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df["age"]

0         45
1         47
2       <NA>
3         62
4       <NA>
        ...
1995      27
1996      41
1997      26
1998      42
1999      59
Name: age, Length: 2000, dtype: Int64

##### 18.Identify unrealistic age values using NumPy/Pandas and replace them with
##### NaN.

In [123]:
import numpy as np
df.loc[(df["age"]<1) |(df["age"]>100),"age"]=np.nan
df["age"]

0         45
1         47
2       <NA>
3         62
4       <NA>
        ...
1995      27
1996      41
1997      26
1998      42
1999      59
Name: age, Length: 2000, dtype: Int64

##### 19.Clean the credit_score column by removing text such as "pts" and converting
##### the column to numeric.

#### 19.Clean the credit_score column by removing text such as "pts" and converting
#### the column to numeric.

In [124]:
df["credit_score"]=df["credit_score"].str.replace("pts","")
df["credit_score"]=pd.to_numeric(df["credit_score"],errors="coerce")
df["credit_score"]

0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit_score, Length: 2000, dtype: float64

##### 20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.

In [125]:
import pandas as pd
import numpy as np

# Calculate Q1
Q1 = df["income_usd"].quantile(0.25)

# Calculate Q3
Q3 = df["income_usd"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Calculate lower and upper boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Find outliers
outliers = df[
    (df["income_usd"] < lower_bound) |
    (df["income_usd"] > upper_bound)
]

# Display results
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("Number of outliers:", len(outliers))

print("\nOutliers:")
print(outliers[["income_usd"]])

Q1: 38185.456855
Q3: 82369.306105
IQR: 44183.84925
Lower Bound: -28090.317020000002
Upper Bound: 148645.07997999998
Number of outliers: 77

Outliers:
       income_usd
65    248156.7141
101   204783.9818
116   785035.6703
137   211200.5187
141   159459.9568
...           ...
1846  327022.9582
1852  795063.7968
1914  168194.0797
1918  234262.1061
1936  258343.5457

[77 rows x 1 columns]

##### 21.Detect outliers in credit_score using the IQR method.

In [126]:
Q1=df["credit_score"].quantile(0.25)
Q3=df["credit_score"].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
outlier=df[(df["credit_score"]<lower_bound)|(df["credit_score"]>upper_bound)]
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("Number of outliers:", len(outliers))
print("\nOutliers:")
print(outliers[["credit_score"]])

Q1: 588.5711718
Q3: 708.9045481
IQR: 120.33337630000005
Lower Bound: 408.0711073499999
Upper Bound: 889.4046125500001
Number of outliers: 77

Outliers:
      credit_score
65      599.236543
101            NaN
116     665.763448
137     615.126374
141     661.014409
...            ...
1846    618.323201
1852    658.993309
1914    590.000000
1918    644.176226
1936    585.240778

[77 rows x 1 columns]

##### 22.Detect suspicious values such as -999 and 99999 in tenure_years and satisfaction.

In [127]:
print("tenure_years:")
print(df["tenure_years"].isin([-999,99999]).sum())
print("satisfaction")
print(df["satisfaction"].isin([-999,99999]).sum())

tenure_years:
10
satisfaction
10

##### 23.Replace invalid/suspicious numerical values with NaN.

In [128]:
import numpy as np
df["tenure_years"]=df["tenure_years"].replace({-999:np.nan,99999:np.nan})
df["satisfaction"]=df["satisfaction"].replace({-999:np.nan,99999:np.nan})

##### 24.Fill missing numerical values using the median of each numerical column.

In [129]:
# Select numerical columns
numeric_cols = df.select_dtypes(include="number").columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

##### 25.Fill missing categorical values using the mode of each categorical column.

In [130]:
categorical_cols = df.select_dtypes(include="object").columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])
print(df[categorical_cols].isna().sum())

customer_id         0
city                0
customer_segment    0
gender              0
is_active           0
churn_flag          0
signup_date         0
lead_source         0
notes_text          0
dtype: int64

##### 26.Clean the signup_date column, which contains multiple date formats and
##### invalid dates, and convert it to Pandas datetime.

In [133]:
df["signup_date"]=pd.to_datetime(df["signup_date"],errors="coerce",format="mixed")
df["signup_date"].head(10)

0   2026-03-11
1          NaT
2   2024-09-20
3   2023-07-12
4   2024-08-06
5   2024-07-21
6   2023-08-14
7          NaT
8   2021-03-08
9   2024-09-10
Name: signup_date, dtype: datetime64[ns]

###### 27.Find rows where signup_date could not be converted into a valid date.

In [135]:
df["signup_date"].isna()

0       False
1        True
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: signup_date, Length: 2000, dtype: bool

##### 28.Clean the lead_source column by standardizing values such as Website,
##### website, WEB, Referral, referral , Google Ads, and google_ads.

In [136]:
df["lead_source"] = df["lead_source"].str.strip().str.lower()

df["lead_source"] = df["lead_source"].replace({
    "website": "Website",
    "web": "Website",
    "referral": "Referral",
    "google ads": "Google Ads",
    "google_ads": "Google Ads"
})

In [137]:
df["lead_source"]

0       Referral
1        Website
2          email
3        Website
4       Referral
          ...
1995       email
1996     Website
1997     Website
1998       email
1999         ???
Name: lead_source, Length: 2000, dtype: object

##### 29.Create a final cleaned DataFrame containing:
##### • cleaned column names
##### • no duplicate IDs
##### • standardized categorical values
##### • numeric columns converted to numeric types
##### • invalid values converted to NaN
##### • missing values handled
##### • detected outliers handled

In [138]:
import pandas as pd
import numpy as np

# Create final cleaned DataFrame
df_clean = df.copy()


# 1. Clean column names
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)


# 2. Remove duplicate IDs
df_clean = df_clean.drop_duplicates(subset="customer_id")


# 3. Convert numerical columns to numeric
numeric_cols = [
    "age",
    "income_usd",
    "credit_score",
    "tenure_years",
    "monthly_visits",
    "satisfaction"
]

for col in numeric_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")


# 4. Convert invalid values to NaN
df_clean[numeric_cols] = df_clean[numeric_cols].replace(
    [-999, 99999],
    np.nan
)


# 5. Clean categorical columns
categorical_cols = [
    "customer_segment",
    "gender",
    "is_active"
]

for col in categorical_cols:
    df_clean[col] = df_clean[col].str.strip().str.lower()


# 6. Clean lead_source
df_clean["lead_source"] = (
    df_clean["lead_source"]
    .str.strip()
    .str.lower()
)

df_clean["lead_source"] = df_clean["lead_source"].replace({
    "website": "Website",
    "web": "Website",
    "referral": "Referral",
    "google ads": "Google Ads",
    "google_ads": "Google Ads"
})


# 7. Convert signup_date to datetime
df_clean["signup_date"] = pd.to_datetime(
    df_clean["signup_date"],
    errors="coerce",
    format="mixed"
)


# 8. Fill missing numerical values with median
df_clean[numeric_cols] = df_clean[numeric_cols].fillna(
    df_clean[numeric_cols].median()
)


# 9. Fill missing categorical values with mode
for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna(
        df_clean[col].mode()[0]
    )


# 10. Handle outliers using IQR
for col in numeric_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_clean[col] = df_clean[col].clip(lower, upper)


# Final cleaned DataFrame
print(df_clean.head())

  customer_id  age   income_usd  credit_score  tenure_years  monthly_visits  \
0  CUST-01861   45  28198.41033    660.562918      5.274076             5.0
1  CUST-00354   47  61312.83129    828.660843      5.632826             9.0
2  CUST-01334   37  44199.67124    613.132775      4.683845             8.0
3  CUST-00906   61  56259.90961    720.236986      2.029634             4.0
4  CUST-01290   37  31238.64196    549.183252      2.648626             5.0

   satisfaction       city customer_segment gender is_active churn_flag  \
0      3.382150       Pune         consumer   male       nan         no
1      3.742125  Hyderabad         consumer   male       nan         no
2      4.195157     Mumbai         consumer   male       nan         no
3      3.742125    Chennai       enterprise   male       nan         no
4      3.117326     Mumbai       enterprise   male       nan         no

  signup_date lead_source        notes_text
0  2026-03-11    Referral            normal
1         NaT     Website  follow-up needed
2  2024-09-20       email            normal
3  2023-07-12     Website            normal
4  2024-08-06    Referral               ???