##### 30 practical data-cleaning questions
##### Basic Cleaning
##### 1. Load the CSV file using Pandas and display the first 10 rows.

In [157]:
import pandas as pd
df=pd.read_csv("C:\\Users\\hp\\Downloads\\messy_customer_loan_dataset - messy_customer_loan_dataset.csv")
df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes
5,CUST100925,32,317590,690,Salaried,Graduate,M,Mumbai,Premium,Auto,235549,120,5,0.46,No
6,CUST100758,39,322966,707,Contract,Graduate,Married,Chennai,Mass,Personal,563319,24,7,0.323,No
7,CUST100793,54,999108,689,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783,48,NaN,0.233,Yes
8,CUST100965,65,478191,758,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872,72,5,0.375,No
9,CUST101198,67,1063307,774,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693,120,2,0.394,Yes

##### 2. Display the number of rows and columns in the dataset.

In [158]:
print("No of rows=",df.shape[0])
print("No of columns=",df.shape[1])

No of rows= 1535
No of columns= 15

##### 3. Display all column names and identify which column names have
##### leading/trailing spaces.

In [159]:
df.columns

Index(['Customer ID', 'Age', 'Annual Income', 'credit Score',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan Amount (INR)', 'tenure Months',
       'Monthly Visits', 'debt_to_income', 'Loan Approved?'],
      dtype='object')

##### 4. Clean all column names by removing extra spaces and converting them into a
##### consistent format such as snake_case.

In [160]:
df.columns=df.columns.str.strip().str.replace(" ","_")

In [161]:
df.columns

Index(['Customer_ID', 'Age', 'Annual_Income', 'credit_Score',
       'Employment-Type', 'Education__Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan_Amount_(INR)', 'tenure_Months',
       'Monthly_Visits', 'debt_to_income', 'Loan_Approved?'],
      dtype='object')

##### 5. Check the data type of every column.

In [162]:
df.dtypes

Customer_ID          object
Age                  object
Annual_Income        object
credit_Score         object
Employment-Type      object
Education__Level     object
marital_status       object
city                 object
customer_segment     object
loan_type            object
Loan_Amount_(INR)    object
tenure_Months         int64
Monthly_Visits       object
debt_to_income       object
Loan_Approved?       object
dtype: object

##### 6. Find the total number of missing values in each column.

In [163]:
df.isnull().sum()

Customer_ID            0
Age                   71
Annual_Income         84
credit_Score          77
Employment-Type       60
Education__Level      46
marital_status         0
city                  52
customer_segment       0
loan_type              0
Loan_Amount_(INR)    102
tenure_Months          0
Monthly_Visits        55
debt_to_income        89
Loan_Approved?         0
dtype: int64

##### 7. Find the percentage of missing values in each column.

In [164]:
percentage=round(df.isnull().sum()/len(df)*100,2)
percentage

Customer_ID          0.00
Age                  4.63
Annual_Income        5.47
credit_Score         5.02
Employment-Type      3.91
Education__Level     3.00
marital_status       0.00
city                 3.39
customer_segment     0.00
loan_type            0.00
Loan_Amount_(INR)    6.64
tenure_Months        0.00
Monthly_Visits       3.58
debt_to_income       5.80
Loan_Approved?       0.00
dtype: float64

##### 8. Find all rows where Age is missing.

In [165]:
missing_rows=df["Age"].isnull()
missing_rows

0       False
1       False
2       False
3       False
4       False
        ...
1530    False
1531    False
1532    False
1533    False
1534    False
Name: Age, Length: 1535, dtype: bool

##### 9. Find all rows where Annual Income is missing.

In [166]:
df["Annual_Income"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
1530    False
1531    False
1532     True
1533    False
1534     True
Name: Annual_Income, Length: 1535, dtype: bool

##### 10.Remove completely duplicate rows and report how many duplicate rows were removed.

In [167]:
duplicate_count=df.duplicated().sum()
print("Total duplicates=",duplicate_count)
df=df.drop_duplicates()
df

Total duplicates= 35

,Customer_ID,Age,Annual_Income,credit_Score,Employment-Type,Education__Level,marital_status,city,customer_segment,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits,debt_to_income,Loan_Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40,477723,719,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455,48,NaN,0.569,No
1531,CUST101295,65,1394481,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828,120,8,0.344,Yes
1532,CUST100861,66,NaN,686,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9,0.084,Yes
1533,CUST101460,45,543340,720,Business,Graduate,Married,Pune,Mass,Education,302389,72,9,0.089,No
1534,CUST101127,61,NaN,731,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995,12,5,0.259,No

##### Data Type & Invalid Values
##### 11.The Age column contains numbers as well as values like "unknown" and
##### "twenty five". Clean this column and convert it into a proper numeric column.

In [168]:
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
df["Age"]

0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: Age, Length: 1500, dtype: float64

##### 12.The Annual Income column contains values such as 650000 INR, ₹720000,
##### 1.2L, and N/A. Clean the column and convert the valid values into numeric
##### format.

In [169]:
df["Annual_Income"]=df["Annual_Income"].astype(str)
df["Annual_Income"]=df["Annual_Income"].str.strip().str.replace("INR","").str.replace("₹","").str.replace("L","")
df["Annual_Income"]=pd.to_numeric(df["Annual_Income"],errors="coerce")
df["Annual_Income"]

0        297809.0
1       1048283.0
2       1043481.0
3        369591.0
4        666989.0
          ...
1530     477723.0
1531    1394481.0
1532          NaN
1533     543340.0
1534          NaN
Name: Annual_Income, Length: 1500, dtype: float64

##### 13.Clean the Credit Score column and identify values that cannot be converted
##### into numbers.

In [170]:
df["credit_Score"]=pd.to_numeric(df["credit_Score"],errors="coerce")
df["credit_Score"]

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531      0.0
1532    686.0
1533    720.0
1534    731.0
Name: credit_Score, Length: 1500, dtype: float64

##### 14.The Loan Amount column contains currency symbols, text, and numeric
##### values. Remove the unwanted characters and convert it into numeric format.

In [171]:
df["Loan_Amount_(INR)"]=df["Loan_Amount_(INR)"].astype(str)
df["Loan_Amount_(INR)"]=df["Loan_Amount_(INR)"].str.strip().str.replace("₹","").str.replace("INR","").str.replace(",","")
df["Loan_Amount_(INR)"]=pd.to_numeric(df["Loan_Amount_(INR)"],errors="coerce")
df["Loan_Amount_(INR)"]

0         378342.0
1         751792.0
2         892792.0
3         908250.0
4         386370.0
           ...
1530     1106455.0
1531      222828.0
1532    50000000.0
1533      302389.0
1534      753995.0
Name: Loan_Amount_(INR), Length: 1500, dtype: float64

##### 15.The Monthly Visits column contains values such as "five", "N/A", and "-".
##### Convert valid values into numeric values and handle invalid values.

In [172]:
df["Monthly_Visits"]=df["Monthly_Visits"].astype(str)
df["Monthly_Visits"]=df["Monthly_Visits"].str.strip().replace({"five":"5","N/A":"None","-":"None","unknown":"None"})
df["Monthly_Visits"]=pd.to_numeric(df["Monthly_Visits"],errors="coerce")
df["Monthly_Visits"]

0        3.0
1       11.0
2        4.0
3       10.0
4        4.0
        ...
1530     NaN
1531     8.0
1532     9.0
1533     9.0
1534     5.0
Name: Monthly_Visits, Length: 1500, dtype: float64

##### 16.Clean the Debt to Income column where some values are written like 35%
##### and 0.4x. Convert the valid values into a consistent numeric format.

In [173]:
df["debt_to_income"] = df["debt_to_income"].astype(str)
df["debt_to_income"] = df["debt_to_income"].str.strip()
df["debt_to_income"] = df["debt_to_income"].replace("%", "").replace("x", "")
df["debt_to_income"] = pd.to_numeric(df["debt_to_income"],errors="coerce")
df["debt_to_income"]

0       0.258
1       0.558
2         NaN
3       0.356
4       0.169
        ...
1530    0.569
1531    0.344
1532    0.084
1533    0.089
1534    0.259
Name: debt_to_income, Length: 1500, dtype: float64

##### 17.After cleaning the numerical columns, check which columns are still stored as
##### object data type.

In [174]:
df.select_dtypes(include="object").columns

Index(['Customer_ID', 'Employment-Type', 'Education__Level', 'marital_status',
       'city', 'customer_segment', 'loan_type', 'Loan_Approved?'],
      dtype='object')

##### Categorical Cleaning
##### 18.Find all unique values in the Employment-Type column.

In [175]:
df["Employment-Type"].unique()

array(['Self-Employed', 'Contract', 'Salaried', 'SALARIED',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

##### 19.Standardize the Employment-Type column so that values such as salaried,
##### SALARIED, and Salaried become one consistent value.

In [176]:
df["Employment-Type"] = df["Employment-Type"].astype(str)
df["Employment-Type"] = df["Employment-Type"].str.strip().str.lower()
df["Employment-Type"]

0       self-employed
1            contract
2       self-employed
3            salaried
4       self-employed
            ...
1530    self-employed
1531    self-employed
1532         contract
1533         business
1534         salaried
Name: Employment-Type, Length: 1500, dtype: object

##### 20.Clean the Education Level column and make values such as graduate,
##### GRADUATE, and Graduate consistent.

In [177]:
df["Education__Level"]=df["Education__Level"].astype(str)
df["Education__Level"]=df["Education__Level"].str.strip().str.lower()
df["Education__Level"]

0               12th
1           graduate
2       postgraduate
3           graduate
4           graduate
            ...
1530        graduate
1531            12th
1532           other
1533        graduate
1534    postgraduate
Name: Education__Level, Length: 1500, dtype: object

##### 21.Clean the City column. Identify incorrect or inconsistent values such as
##### hyderbad, Hyd, Bangalore, and Bengaluru.

In [178]:
df["city"]=df["city"].astype(str)
df["city"]=df["city"].str.strip().str.lower().replace({"hyd":"hyderbad","bengaluru":"banglore","hyderabad":"hyderbad","bangalore":"banglore"})
df["city"]

0         mumbai
1         jaipur
2        kolkata
3        kolkata
4       hyderbad
          ...
1530      jaipur
1531      jaipur
1532       delhi
1533        pune
1534     chennai
Name: city, Length: 1500, dtype: object

##### 22.Find all unique values in the Customer Segment column and identify invalid
##### categories.

In [179]:
df["customer_segment"].unique()

array(['Mass', 'PREMIUM', 'Affluent', 'Premium', 'SME', 'premium',
       'unknown', 'High Value', 'mass'], dtype=object)

##### 23.Clean the Loan Type column so that values such as personal, PERSONAL,
##### and personal loan are standardized.

In [184]:
df["loan_type"] = df["loan_type"].astype(str)
df["loan_type"] = df["loan_type"].str.strip().str.lower().str.replace("personal loan", "personal").str.replace("home loan","home")
df["loan_type"] = df["loan_type"].str.capitalize()
df["loan_type"]

0       Education
1            Auto
2            Auto
3            Home
4       Education
          ...
1530         Home
1531     Personal
1532     Personal
1533    Education
1534    Education
Name: loan_type, Length: 1500, dtype: object