##### Exam Task on Pandas Method (Data Cleaning)
##### 
##### Part 1 — Inspect & Understand the Dataset
##### Q1. Load the dataset
##### Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
##### Then display the first 10 rows.
##### Use: pd.read_csv(), head()

In [196]:
import pandas as pd
df=pd.read_csv("C:\\Users\\hp\\Downloads\\customer_analytics - customer_analytics.csv")
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

##### Q2. Inspect the end of the dataset
##### Display the last 15 rows.
##### Use: tail()

In [197]:
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

##### Q3. Random inspection
##### Display 10 random records.
##### Use: sample()

In [198]:
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
501,101133,54,32788,281524.12,394,5,Delhi,Premium,Mobile,NaN,Yes,High,21852.59,20,4.2
1700,101770,59,211987,180740.95,405,8,Delhi,Corporate,Online,2025-06-08 00:00:00,Yes,High,41062.19,14,4.7
1009,100139,29,177267,26460.51,743,12,Pune,Corporate,Branch,2025-11-30 00:00:00,No,Low,13410.02,148,2.4
118,101259,19,169129,234166.81,516,9,Bangalore,Retail,Online,NaN,Yes,High,29836.6,38,1.8
67,101469,58,42069,abc,560,14,Kolkata,Premium,Agent,2023-11-07 00:00:00,Yes,Medium,4691.16,63,9.4
1214,101776,54,234184,40524.04,369,14,Hyderabad,Corporate,Mobile,2023-07-21 00:00:00,No,High,33040.96,79,9.9
1240,100709,30,43743,93858.95,703,12,Kolkata,Premium,Online,2022-10-31 00:00:00,No,Low,49910.8,55,4.6
1361,101175,NaN,122661,284623.32,417,9,Kolkata,SME,Branch,2024-05-07 00:00:00,Yes,High,39947.12,25,7.0
364,100734,not_available,62384,235458.55,707,5,Mumbai,NaN,Branch,2025-05-29 00:00:00,Yes,Low,17526.05,32,7.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5

##### Q4. Dataset audit
##### Use info() to identify:
##### • Number of rows
##### • Number of columns
##### • Columns with missing values
##### • Columns having incorrect/object datatypes
##### Use: info()

In [199]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

##### Q5. Missing-value audit
##### Calculate the number of missing values in every column.
##### Then verify the result using both:
##### isnull()
##### and
##### isna()

In [200]:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [201]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

##### Part 2 — Detect & Fix Data Quality Problems
##### Q6. Duplicate investigation
##### Find how many duplicate rows exist.
##### Do not remove them yet.
##### Use: duplicated()

In [202]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

##### Q7. Remove duplicates
##### Remove all duplicate records and store the cleaned result back into df.
##### Then verify that duplicates no longer exist.
##### Use: drop_duplicates(), duplicated()

In [203]:
df=df.drop_duplicates()
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [204]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2000, dtype: bool

##### Q8. Numeric column investigation
##### Select only numeric columns.
##### Identify which columns are currently numeric and which potentially numeric columns have
##### become object because of invalid values.
##### Use: select_dtypes()

In [205]:
df.select_dtypes(include="number")

      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2000 rows x 3 columns]

##### Q9. Fix Age
##### The Age column contains:
##### • Valid numbers
##### • Missing values
##### • Invalid text such as unknown, N/A, etc.
##### Convert Age into a proper numeric column.
##### Invalid values should become missing values.
##### Then fill missing Age values using the median age.

In [206]:
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
df["Age"]

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64

In [207]:
age_median=df["Age"].median()

In [208]:

age_median=df["Age"].fillna(age_median)
age_median

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64

##### Q10. Fix Annual Income
##### Clean Annual_Income.
##### Requirements:
##### 1. Convert invalid values to missing.
##### 2. Convert the column to a numeric datatype.
##### 3. Calculate the median.
##### 4. Fill missing values using the median.
##### Use: pd.to_numeric(), median(), fillna(), astype()

In [209]:
df["Annual_Income"]=pd.to_numeric(df["Annual_Income"],errors="coerce")

In [210]:
df["Annual_Income"]=df["Annual_Income"].astype("float")
median_income=df["Annual_Income"].median()
median_income

139914.0

In [211]:
df["Annual_Income"]=df["Annual_Income"].fillna(median_income)
df["Annual_Income"]

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2000, dtype: float64

##### Part 3 — Numerical Cleaning
##### Q11. Clean Account Balance
##### The Account_Balance column contains invalid strings and missing values.
##### Clean the column and replace missing values with the mean Account Balance.
##### Use:
##### • pd.to_numeric()
##### • mean()
##### • fillna()

In [212]:
df["Account_Balance"]=pd.to_numeric(df["Account_Balance"],errors="coerce")

In [213]:
balance_mean=df["Account_Balance"].mean()

In [214]:
df["Account_Balance"]=df["Account_Balance"].fillna(balance_mean)
df["Account_Balance"]

0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2000, dtype: float64

##### Q12. Clean Credit Score
##### Clean Credit_Score.
##### Invalid values should become missing.
##### Then replace missing values with the median Credit Score.
##### Finally convert the column to integer.
##### Use:
##### • pd.to_numeric()
##### • median()
##### • fillna()
##### • astype()

In [215]:
df["Credit_Score"]=pd.to_numeric(df["Credit_Score"],errors="coerce")
median_credit_Score=df["Credit_Score"].median()
df["Credit_Score"]=df["Credit_Score"].fillna(median_credit_Score)
df["Credit_Score"]=df["Credit_Score"].astype("int")
df["Credit_Score"]

0       772
1       374
2       668
3       315
4       370
       ...
2035    677
2036    392
2037    737
2038    794
2039    783
Name: Credit_Score, Length: 2000, dtype: int64

##### Q13. Clean Monthly Spend
##### Clean Monthly_Spend.
##### Then:
##### • Convert it to numeric.
##### • Replace invalid values.
##### • Replace missing values using the median.
##### • Make sure the final column is numeric.

In [216]:
df["Monthly_Spend"]=pd.to_numeric(df["Monthly_Spend"],errors="coerce")
median_Monthly_Spend=df["Monthly_Spend"].median()
df["Monthly_Spend"]=df["Monthly_Spend"].fillna(median_Monthly_Spend)
df["Monthly_Spend"]

0       23066.19
1       24625.17
2       28536.34
3       12869.71
4       34163.02
          ...
2035     8455.42
2036    34087.69
2037    26518.74
2038    20943.11
2039    48511.32
Name: Monthly_Spend, Length: 2000, dtype: float64

##### Q14. Clean Transactions
##### The Transactions column contains invalid strings.
##### Convert it to numeric and replace invalid values with the median number of transactions.
##### Then convert the final column to integer.

In [217]:
df["Transactions"]=pd.to_numeric(df["Transactions"],errors="coerce")
median_Transactions=df["Transactions"].median()
df["Transactions"]=df["Transactions"].fillna(median_Transactions)
df["Transactions"]=df["Transactions"].astype("int")
df["Transactions"]

0       135
1       106
2       146
3       115
4        94
       ...
2035    119
2036    134
2037     87
2038    107
2039    119
Name: Transactions, Length: 2000, dtype: int64

##### Q15. Clean Satisfaction Score
##### Clean Satisfaction_Score.
##### Replace missing/invalid values using the mean Satisfaction Score.
##### Then convert the column to float.

In [218]:
df["Satisfaction_Score"]=pd.to_numeric(df["Satisfaction_Score"],errors="coerce")
mean_Satisfaction_Score=df["Satisfaction_Score"].mean()
df["Satisfaction_Score"]=df["Satisfaction_Score"].fillna(mean_Satisfaction_Score)
df["Satisfaction_Score"]=df["Satisfaction_Score"].astype("float")
df["Satisfaction_Score"]

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64

##### Part 4 — Date Cleaning
##### Q16. Investigate Join_Date
##### Inspect the Join_Date column.
##### Identify the problems caused by:
##### • Missing dates
##### • Different date formats
##### • Invalid date strings
##### Do not clean it yet.

In [275]:
print("Data type:", df["Join_Date"].dtype)

print("Missing values:", df["Join_Date"].isnull().sum())

print("Unique values:", df["Join_Date"].nunique())

print(df["Join_Date"].unique())

Data type: datetime64[ns]
Missing values: 0
Unique values: 1222
<DatetimeArray>
['2022-08-15 00:00:00', '2025-01-11 00:00:00', '2024-08-01 00:00:00',
 '2021-05-15 00:00:00', '2026-02-03 00:00:00', '2023-06-04 00:00:00',
 '2024-01-16 00:00:00', '2024-06-26 00:00:00', '2025-03-12 00:00:00',
 '2021-10-07 00:00:00',
 ...
 '2025-07-07 00:00:00', '2023-09-03 00:00:00', '2023-04-08 00:00:00',
 '2022-07-02 00:00:00', '2023-07-26 00:00:00', '2024-11-03 00:00:00',
 '2022-11-30 00:00:00', '2025-09-10 00:00:00', '2022-10-17 00:00:00',
 '2023-08-26 00:00:00']
Length: 1222, dtype: datetime64[ns]

##### Q17. Convert Join_Date
##### Convert Join_Date into a proper Pandas datetime column.
##### Any invalid dates should become missing values.
##### Use: pd.to_datetime()

In [276]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)

print(df["Join_Date"].dtype)

datetime64[ns]

###### Q18. Handle missing dates
###### After conversion, find how many missing dates remain.
###### Then replace missing dates appropriately using a reasonable date-based strategy.

In [279]:
print("Missing dates:", df["Join_Date"].isnull().sum())

median_date = df["Join_Date"].median()

df["Join_Date"] = df["Join_Date"].fillna(median_date)

print("Missing dates after filling:",
      df["Join_Date"].isnull().sum())

Missing dates: 0
Missing dates after filling: 0

##### Part 5 — Categorical Cleaning
##### Q19. Clean City
##### The City column contains values such as:
##### Mumbai
##### mumbai
##### Mumbai
##### mumbai
##### Standardize the values so that logically identical cities are represented consistently.
##### Then check the unique frequency distribution.
##### Use: replace(), value_counts()

In [ ]:
df["City"] = df["City"].replace({
    "banglore":"Bangalore",
    "Banglore":"Bangalore",
    "mumbai": "Mumbai",
    "MUMBAI": "Mumbai",
    "pune": "Pune",
    "PUNE": "Pune",
    "delhi": "Delhi",
    "DELHI": "Delhi",
    "chennai":"Chennai",
    "CHENNAI":"Chennai",
    "kolkata":"Kolkata",
    "KOLKATA":"Kolkata",
    "HYDERABAD":"Hyderabad",
    "hyderabad":"Hyderabad"
    
})
print(df["City"].value_counts())

##### Q20. Analyze Segment
##### Check the frequency of:
##### Retail
##### SME
##### Corporate
##### Premium
##### Also determine whether missing values exist.
##### Then replace missing Segment values with the most appropriate category based on your
##### analysis.
##### Use: value_counts(), fillna()

In [ ]:
df["Segment"].value_counts(dropna=False)

In [ ]:
most_common = df["Segment"].value_counts().idxmax()
print(most_common)

In [ ]:
df["Segment"]=df["Segment"].fillna(most_common)
df["Segment"]

##### Q21. Clean Active
##### Active is supposed to be a binary column, but it contains:
##### Yes
##### No
##### Y
##### N
##### YES
##### NO
##### yes
##### no
##### 1
##### 0
##### Transform these into a consistent representation:
##### Yes
##### No
##### Then verify the result with value_counts().
##### Use: replace(), value_counts()

In [ ]:
df["Active"]=df["Active"].replace({"Y":"Yes","yes":"Yes","N":"No","no":"No","1":"Yes","0":"No","YES":"Yes","NO":"No"})
df["Active"].value_counts()

##### Q22. Clean Risk_Level
##### Check the distribution of:
##### High
##### Medium
##### Low
##### Verify whether missing values exist.
##### Then display the final class distribution.

In [ ]:
print(df["Risk_Level"].value_counts())

In [ ]:
print(df["Risk_Level"].isnull().sum())

In [ ]:
print(df["Risk_Level"].value_counts())

##### Part 6 — Column Transformation
##### Q23. Rename columns
##### Rename these columns:
##### Customer_ID → Customer_ID
##### Annual_Income → AnnualIncome
##### Account_Balance → AccountBalance
##### Credit_Score → CreditScore
##### Tenure_Years → Tenure
##### Join_Date → CustomerJoinDate
##### Risk_Level → RiskLevel
##### Monthly_Spend → MonthlySpend
##### Satisfaction_Score → SatisfactionScore
##### Use rename().

In [ ]:
df=df.rename(columns={
    "Customer_ID":"Customer_ID",
    "Annual_Income":"AnnualIncome",
    "Account_Balance":"AccountBalance",
    "Credit_Score":"CreditScore",
    "Tenure_Years":"Tenure",
    "Join_Date":"CustomerJoinDate",
    "Risk_Level":"RiskLevel",
    "Monthly_Spend":"MonthlySpend",
    "Satisfaction_Score":"SatisfactionScore"
})
print(df.columns)

##### Q24. Add a prefix
##### Add:
##### Customer_
##### to every column.
##### Example:
##### Age
##### becomes:
##### Customer_Age
##### Use: add_prefix()

In [ ]:
df.add_prefix("Customer_")

##### Q25. Remove unnecessary column
##### Determine whether Customer_ID should be retained for analysis.
##### Create a cleaned DataFrame without the identifier column.
##### Use: drop()

In [ ]:
df.drop("Customer_ID", axis=1,inplace=True)

In [ ]:
df

##### Part 7 — Create New Columns
##### Q26. Create Annual Income in Lakhs
##### Create:
##### Income_Lakhs
##### using:
##### AnnualIncome / 100000
##### Then check the first 10 records.

In [ ]:
df["Income_Lakhs"]=df["AnnualIncome"]/100000
df.head(10)

##### Q27. Create Monthly Income
##### Create:
##### MonthlyIncome
##### using:
##### AnnualIncome / 12
##### Then create:
##### Income_After_Spending
##### using:
##### MonthlyIncome - MonthlySpend

In [ ]:
df["MonthlyIncome"]=df["AnnualIncome"]/12
df["Income_After_Spending"]=df["MonthlyIncome"]-df["MonthlySpend"]
df.head(10)

##### Q28. Create Balance-to-Income Ratio
##### Create:
##### Balance_Income_Ratio
##### using:
##### AccountBalance / AnnualIncome
##### Then inspect the first 10 rows.
##### Think carefully about division by zero and missing values.

In [ ]:
df["Balance_Income_Ratio"]=df["AccountBalance"]/df["AnnualIncome"]
df.head(10)

In [280]:
df.to_csv("customer_analytics.csv",index=False)